### ISSUE TITLE
install error in apt-get update

### ISSUE THREAD

**Issue by jsoh8088** [NVIDIA/nvidia-docker#718] opened 2018-04-26 11:59 UTC
I followed the install nvidia-docker2 steps( https://github.com/NVIDIA/nvidia-docker], but problems happened when i input `sudo apt-get update`.

```
W: Failed to fetch https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64/Packages  gnutls_handshake() failed: Handshake failed

W: Failed to fetch https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/amd64/Packages  gnutls_handshake() failed: Handshake failed

W: Failed to fetch https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64/Packages  gnutls_handshake() failed: Handshake failed

E: Some index files failed to download. They have been ignored, or old ones used instead
```.

kernel version : Linux DSLab-GPU 4.4.0-109-generic #132~14.04.1-Ubuntu SMP Tue Jan 9 21:46:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Nvidia-smi: Successfully executed.
docker version : 18.04.0-ce
Ubuntu version : Ubuntu 14.04

 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by flx42** [comment] 2018-04-26 22:16
Duplicate of #714, I've contacted GitHub.

**Closed by flx42** 2018-04-26 22:16 UTC
