### ISSUE TITLE
Devices Flag not Set if No Volumes Needed

### ISSUE THREAD

**Issue by cancan101** [NVIDIA/nvidia-docker#44] opened 2016-02-03 17:40 UTC
Right now [`GenerateLocalArgs` does not get called if no volumes are needed]( https://github.com/NVIDIA/nvidia-docker/blob/fda10b2d27bf5578cc5337c23877f827e4d1ed77/tools/src/nvidia-docker/main.go#L38-L52) which means the devices flag is not set.

This causes issues for images that expect the CUDA devices to exist. ([see for example Tensorflow](https://github.com/tensorflow/tensorflow/blob/4c717c6ac35519e6d5eef11b9b5384847e5fdd89/tensorflow/stream_executor/cuda/cuda_diagnostics.cc#L100-L112)).

This is different from the [original version which did set the flag](https://github.com/NVIDIA/nvidia-docker/blob/e71f8ce3b53123289df78cf8ece6070c23c0ab61/nvidia-docker#L141).

**Comment by 3XX0** [comment] 2016-02-03 18:58
This is an intended behavior as non-GPU images shouldn't have devices set.
Moreover, device files are unusable without their corresponding volumes.

Tensorflow [uses the official CUDA images](https://github.com/tensorflow/tensorflow/blob/4c717c6ac35519e6d5eef11b9b5384847e5fdd89/tensorflow/tools/docker/Dockerfile.gpu#L1) which sets the volumes.needed label. You are probably encountering this issue because you used an outdated Tensorflow image.

**Comment by cancan101** [comment] 2016-02-03 19:05
If you take a look at: https://github.com/tensorflow/tensorflow/blob/4c717c6ac35519e6d5eef11b9b5384847e5fdd89/tensorflow/stream_executor/cuda/cuda_diagnostics.cc#L100-L112 you can see the image is explicitly looking for the dev.

**Comment by flx42** [comment] 2016-02-03 19:21
The problem is that the Tensorflow 0.6.0 images were built with an older version of nvidia-docker and official images that didn't include the volume tags.
If you use nvidia-docker with this image, it will be interpreted as a CPU image.

You should either rebuild the Tensorflow image yourself or use the official instructions for Tensorflow (which mean exporting 2 environment variables).
For the next Tensorflow release, they will probably regenerate images based on our new images.

**Comment by 3XX0** [comment] 2016-02-03 21:49
@cancan101: The code you linked is in the CUDA code path, so devices should be there at that point.
However, this code relies on `/proc/driver/nvidia/version` which might not be there depending on the driver version you are using and `/dev/nvidia0` which might not be in the container if you didn't isolate it (device files are not renumbered).

**Closed** 2016-02-05 22:38 UTC
Labels: wontfix
