### ISSUE TITLE
nvidia-docker-plugin exits with "Error: nvml: Unknown Error" - M60

### ISSUE THREAD

**Issue by lmatt-bit** [NVIDIA/nvidia-docker#420] opened 2017-07-06 13:37 UTC
Below is the trace information. 
```
[root@MTAPI ~]# ltrace -f nvidia-docker-plugin                               
[pid 4509] __libc_start_main(0x46bf60, 1, 0x7fff37ab1a78, 0x752bd0 <unfinished ...>
[pid 4509] pthread_once(0xd003a8, 0x728db0, 0x7fff37ab1a88, 0x752bd0 <unfinished ...>
[pid 4509] malloc(104)                                                                                                  = 0x2100010
[pid 4509] pthread_mutexattr_init(0x7fff37ab18d0, 0x2100070, 0x2100010, 0x2100010)                                      = 0
[pid 4509] pthread_mutexattr_settype(0x7fff37ab18d0, 1, 0x2100010, 0x2100010)                                           = 0
[pid 4509] pthread_mutex_init(0xd008c0, 0x7fff37ab18d0, 0x2100010, 0x2100010)                                           = 0
[pid 4509] pthread_mutexattr_destroy(0x7fff37ab18d0, 0x7fff37ab18d0, 0, 0)                                              = 0
[pid 4509] pthread_mutexattr_init(0x7fff37ab18e0, 0x7fff37ab18d0, 0, 0)                                                 = 0
[pid 4509] pthread_mutexattr_settype(0x7fff37ab18e0, 1, 0, 0)                                                           = 0
[pid 4509] pthread_mutex_init(0xd00900, 0x7fff37ab18e0, 0, 0)                                                           = 0
[pid 4509] pthread_mutexattr_destroy(0x7fff37ab18e0, 0x7fff37ab18e0, 0, 0)                                              = 0
[pid 4509] __cxa_atexit(0x72a7f0, 0, 0, 0)                                                                              = 0
[pid 4509] <... pthread_once resumed> )                                                                                 = 0
[pid 4509] __cxa_atexit(0x72a830, 0, 0xcbbaa8, -1)                                                                      = 0
[pid 4509] pthread_attr_init(0x7fff37ab1920, 0x46a640, 0xf8bfbff, 0xcdbce0)                                             = 0
[pid 4509] pthread_attr_getstacksize(0x7fff37ab1920, 0x7fff37ab1918, 0xf8bfbff, 0)                                      = 0
[pid 4509] pthread_attr_destroy(0x7fff37ab1920, 0x7fff37ab1918, 0xf8bfbff, 0)                                           = 0
[pid 4509] malloc(24)                                                                                                   = 0x2100080
[pid 4509] sigfillset(~<31-32>)                                                                                         = 0
[pid 4509] pthread_sigmask(2, 0x7fff37ab1760, 0x7fff37ab17e0, 0x2100080)                                                = 0
[pid 4509] pthread_attr_init(0x7fff37ab1720, 0x7fff37ab1760, 0, 0)                                                      = 0
[pid 4509] pthread_attr_getstacksize(0x7fff37ab1720, 0x7fff37ab1718, 0, 0)                                              = 0
[pid 4509] pthread_create(0x7fff37ab1710, 0x7fff37ab1720, 0x711c40, 0x2100080)                                          = 0
[pid 4510] free(0x2100080, 0, 0xa4d6138f27b96e62, -1 <unfinished ...>
[pid 4509] pthread_sigmask(2, 0x7fff37ab17e0, 0, -1)                                                                    = 0
[pid 4510] <... free resumed> )                                                                                         = 0
[pid 4509] malloc(24)                                                                                                   = 0x2100080
[pid 4509] sigfillset(~<31-32>)                                                                                         = 0
[pid 4509] pthread_sigmask(2, 0x7fff37ab1690, 0x7fff37ab1710, 0x2100070)                                                = 0
[pid 4509] pthread_attr_init(0x7fff37ab1650, 0x7fff37ab1690, 0, 0)                                                      = 0
[pid 4509] pthread_attr_getstacksize(0x7fff37ab1650, 0x7fff37ab1648, 0, 0)                                              = 0
[pid 4509] pthread_create(0x7fff37ab1640, 0x7fff37ab1650, 0x711c40, 0x2100080)                                          = 0
[pid 4509] pthread_sigmask(2, 0x7fff37ab1710, 0, -1 <unfinished ...>
[pid 4511] free(0x2100080, 0, 0xa4d6128f07b96e62, -1)                                                                   = 0
[pid 4509] <... pthread_sigmask resumed> )                                                                              = 0
[pid 4509] malloc(24)                                                                                                   = 0x2100080
[pid 4509] sigfillset( <unfinished ...>
[pid 4511] malloc(24, 0xc820000d80, 0x7f74df2bad88, 0x7f74df2badd0 <unfinished ...>
[pid 4509] <... sigfillset resumed> ~<31-32>)                                                                           = 0
[pid 4509] pthread_sigmask(2, 0x7fff37ab1540, 0x7fff37ab15c0, 0x2100070)                                                = 0
[pid 4509] pthread_attr_init(0x7fff37ab1500, 0x7fff37ab1540, 0, 0)                                                      = 0
[pid 4509] pthread_attr_getstacksize(0x7fff37ab1500, 0x7fff37ab14f8, 0, 0)                                              = 0
[pid 4509] pthread_create(0x7fff37ab14f0, 0x7fff37ab1500, 0x711c40, 0x2100080 <unfinished ...>
[pid 4511] <... malloc resumed> )                                                                                       = 0x7f74d80008c0
[pid 4511] sigfillset(0x7f74df2bac30, 0x7f74d80008d0, 0x43dd30, 0x7f74d80008c0)                                         = 0
[pid 4511] pthread_sigmask(2, 0x7f74df2bac30, 0x7f74df2bacb0, 0x7f74d80008c0)                                           = 0
[pid 4509] <... pthread_create resumed> )                                                                               = 0
[pid 4511] pthread_attr_init(0x7f74df2babf0, 0x7f74df2bac30, 0, 0 <unfinished ...>
[pid 4512] free(0x2100080, 0, 0xa4d6118f67b96e62, -1 <unfinished ...>
[pid 4509] pthread_sigmask(2, 0x7fff37ab15c0, 0, -1 <unfinished ...>
[pid 4512] <... free resumed> )                                                                                         = 0
[pid 4511] <... pthread_attr_init resumed> )                                                                            = 0
[pid 4511] pthread_attr_getstacksize(0x7f74df2babf0, 0x7f74df2babe8, 0, 0 <unfinished ...>
[pid 4509] <... pthread_sigmask resumed> )                                                                              = 0
[pid 4511] <... pthread_attr_getstacksize resumed> )                                                                    = 0
[pid 4511] pthread_create(0x7f74df2babe0, 0x7f74df2babf0, 0x711c40, 0x7f74d80008c0)                                     = 0
[pid 4511] pthread_sigmask(2, 0x7f74df2bacb0, 0, -1 <unfinished ...>
[pid 4513] free(0x7f74d80008c0, 0, 0xa4d6108f47b96e62, -1)                                                              = 0
[pid 4511] <... pthread_sigmask resumed> )                                                                              = 0
[pid 4509] pthread_mutex_lock(0xcffe20, 0xcdbce0, 0xc82004ff18, 0)                                                      = 0
[pid 4509] pthread_cond_broadcast(0xcffe60, 0, 0, 0)                                                                    = 0
[pid 4509] pthread_mutex_unlock(0xcffe20, 1, 0, 0)                                                                      = 0
nvidia-docker-plugin | 2017/07/06 21:35:46 Loading NVIDIA unified memory
[pid 4514] --- Called exec() ---
[pid 4514] __libc_start_main(0x4017a0, 3, 0x7fff3ef78908, 0x401290 <unfinished ...>
[pid 4514] __strdup(0x7fff3ef796f6, 0x7fff3ef78908, 0x7fff3ef78908, 0)                                                  = 0x15ad010
[pid 4514] free(0x15ad010)                                                                                              = <void>
[pid 4514] __strdup(0x7fff3ef796f9, 0x7fff3ef78908, 0x7fff3ef78908, 0)                                                  = 0x15ad010
[pid 4514] __strtol_internal("0", 0x7fff3ef78680, 0)                                                                    = 0
[pid 4514] free(0x15ad010)                                                                                              = <void>
[pid 4514] fopen("/proc/modules", "r")                                                                                  = 0x15ad030
[pid 4514] fscanf(0x15ad030, 0x405a6c, 0x7fff3ef78660, -1)                                                              = 1
[pid 4514] fclose(0x15ad030)                                                                                            = 0
[pid 4514] fopen("/proc/devices", "r")                                                                                  = 0x15ad010
[pid 4514] fgets("Character devices:\n", 255, 0x15ad010)                                                                = 0x7fff3ef78580
[pid 4514] ferror(0x15ad010)                                                                                            = 0
[pid 4514] fgets("  1 mem\n", 255, 0x15ad010)                                                                           = 0x7fff3ef78580
[pid 4514] strstr("  1 mem\n", "nvidia-uvm")                                                                            = nil
[pid 4514] fgets("  4 /dev/vc/0\n", 255, 0x15ad010)                                                                     = 0x7fff3ef78580
[pid 4514] strstr("  4 /dev/vc/0\n", "nvidia-uvm")                                                                      = nil
[pid 4514] fgets("  4 tty\n", 255, 0x15ad010)                                                                           = 0x7fff3ef78580
[pid 4514] strstr("  4 tty\n", "nvidia-uvm")                                                                            = nil
[pid 4514] fgets("  4 ttyS\n", 255, 0x15ad010)                                                                          = 0x7fff3ef78580
[pid 4514] strstr("  4 ttyS\n", "nvidia-uvm")                                                                           = nil
[pid 4514] fgets("  5 /dev/tty\n", 255, 0x15ad010)                                                                      = 0x7fff3ef78580
[pid 4514] strstr("  5 /dev/tty\n", "nvidia-uvm")                                                                       = nil
[pid 4514] fgets("  5 /dev/console\n", 255, 0x15ad010)                                                                  = 0x7fff3ef78580
[pid 4514] strstr("  5 /dev/console\n", "nvidia-uvm")                                                                   = nil
[pid 4514] fgets("  5 /dev/ptmx\n", 255, 0x15ad010)                                                                     = 0x7fff3ef78580
[pid 4514] strstr("  5 /dev/ptmx\n", "nvidia-uvm")                                                                      = nil
[pid 4514] fgets("  7 vcs\n", 255, 0x15ad010)                                                                           = 0x7fff3ef78580
[pid 4514] strstr("  7 vcs\n", "nvidia-uvm")                                                                            = nil
[pid 4514] fgets(" 10 misc\n", 255, 0x15ad010)                                                                          = 0x7fff3ef78580
[pid 4514] strstr(" 10 misc\n", "nvidia-uvm")                                                                           = nil
[pid 4514] fgets(" 13 input\n", 255, 0x15ad010)                                                                         = 0x7fff3ef78580
[pid 4514] strstr(" 13 input\n", "nvidia-uvm")                                                                          = nil
[pid 4514] fgets(" 21 sg\n", 255, 0x15ad010)                                                                            = 0x7fff3ef78580
[pid 4514] strstr(" 21 sg\n", "nvidia-uvm")                                                                             = nil
[pid 4514] fgets(" 29 fb\n", 255, 0x15ad010)                                                                            = 0x7fff3ef78580
[pid 4514] strstr(" 29 fb\n", "nvidia-uvm")                                                                             = nil
[pid 4514] fgets("128 ptm\n", 255, 0x15ad010)                                                                           = 0x7fff3ef78580
[pid 4514] strstr("128 ptm\n", "nvidia-uvm")                                                                            = nil
[pid 4514] fgets("136 pts\n", 255, 0x15ad010)                                                                           = 0x7fff3ef78580
[pid 4514] strstr("136 pts\n", "nvidia-uvm")                                                                            = nil
[pid 4514] fgets("162 raw\n", 255, 0x15ad010)                                                                           = 0x7fff3ef78580
[pid 4514] strstr("162 raw\n", "nvidia-uvm")                                                                            = nil
[pid 4514] fgets("180 usb\n", 255, 0x15ad010)                                                                           = 0x7fff3ef78580
[pid 4514] strstr("180 usb\n", "nvidia-uvm")                                                                            = nil
[pid 4514] fgets("188 ttyUSB\n", 255, 0x15ad010)                                                                        = 0x7fff3ef78580
[pid 4514] strstr("188 ttyUSB\n", "nvidia-uvm")                                                                         = nil
[pid 4514] fgets("189 usb_device\n", 255, 0x15ad010)                                                                    = 0x7fff3ef78580
[pid 4514] strstr("189 usb_device\n", "nvidia-uvm")                                                                     = nil
[pid 4514] fgets("195 nvidia-frontend\n", 255, 0x15ad010)                                                               = 0x7fff3ef78580
[pid 4514] strstr("195 nvidia-frontend\n", "nvidia-uvm")                                                                = nil
[pid 4514] fgets("202 cpu/msr\n", 255, 0x15ad010)                                                                       = 0x7fff3ef78580
[pid 4514] strstr("202 cpu/msr\n", "nvidia-uvm")                                                                        = nil
[pid 4514] fgets("203 cpu/cpuid\n", 255, 0x15ad010)                                                                     = 0x7fff3ef78580
[pid 4514] strstr("203 cpu/cpuid\n", "nvidia-uvm")                                                                      = nil
[pid 4514] fgets("247 nvidia-uvm\n", 255, 0x15ad010)                                                                    = 0x7fff3ef78580
[pid 4514] strstr("247 nvidia-uvm\n", "nvidia-uvm")                                                                     = "nvidia-uvm\n"
[pid 4514] sscanf(0x7fff3ef78580, 0x405b3b, 0x7fff3ef7868c, 4)                                                          = 1
[pid 4514] fclose(0x15ad010)                                                                                            = 0
[pid 4514] __xstat(1, "/dev/nvidia-uvm", 0x7fff3ef78480)                                                                = 0
[pid 4514] __xstat(1, "/dev/nvidia-uvm-tools", 0x7fff3ef78480)                                                          = 0
[pid 4514] +++ exited (status 0) +++
[pid 4509] --- SIGCHLD (Child exited) ---
nvidia-docker-plugin | 2017/07/06 21:35:46 Loading NVIDIA management library
[pid 4509] setenv("CUDA_DISABLE_UNIFIED_MEMORY", "1", 1)                                                                = 0
[pid 4509] setenv("CUDA_CACHE_DISABLE", "1", 1)                                                                         = 0
[pid 4509] unsetenv("\340j\v \310")                                                                                     = <void>
[pid 4509] dlopen("libnvidia-ml.so.1", 257)                                                                             = 0x21009c0
[pid 4509] nvmlInit_v2(0x7f74e06c8908, 0, 0x21009c0, -1)                                                                = 0
nvidia-docker-plugin | 2017/07/06 21:35:46 Discovering GPU devices
[pid 4509] nvmlDeviceGetCount_v2(0xc820074f80, 0xcdbce0, 0xc82004fb40, 0xc82004fba8)                                    = 0
[pid 4509] nvmlDeviceGetHandleByIndex_v2(0, 0xc820086048, 0xc820086048, 0xc82004fa98)                                   = 0
[pid 4509] nvmlDeviceGetName(0x7f74dd865ca8, 0xc82007c4c0, 64, 0xc82007c4c0)                                            = 0
[pid 4509] nvmlDeviceGetUUID(0x7f74dd865ca8, 0xc8200924b0, 80, 0xc8200924b0)                                            = 0
[pid 4509] nvmlDeviceGetMinorNumber(0x7f74dd865ca8, 0xc820074fd0, 0xc820074fd0, 0xc82004fa88)                           = 0
[pid 4509] nvmlDeviceGetPowerManagementLimit(0x7f74dd865ca8, 0xc820074ff0, 0xc820074ff0, 0xc82004fa88)                  = 0
[pid 4509] nvmlDeviceGetPciInfo_v2(0x7f74dd865ca8, 0xc82007c500, 0xc82007c500, 0xc82004fa88)                            = 0
[pid 4509] nvmlDeviceGetBAR1MemoryInfo(0x7f74dd865ca8, 0xc8200b6b20, 0xc8200b6b20, 0xc82004fa70)                        = 0
[pid 4509] nvmlDeviceGetMaxPcieLinkGeneration(0x7f74dd865ca8, 0xc820075050, 0xc820075050, 0xc82004fa88)                 = 0
[pid 4509] nvmlDeviceGetMaxPcieLinkWidth(0x7f74dd865ca8, 0xc820075070, 0xc820075070, 0xc82004fa88)                      = 999
[pid 4509] nvmlErrorString(999, 0xcdbce0, 0xc82004f980, 0xc82004f9f0)                                                   = 0x7f74dd63d374
nvidia-docker-plugin | 2017/07/06 21:35:46 Error: nvml: Unknown Error
[pid 4509] nvmlShutdown(0xc82004faf0, 0xcdbce0, 0xc82004fa98, 0xc82004faf0)                                             = 0
[pid 4509] dlclose(0x21009c0)                                                                                           = 0
[pid 4513] +++ exited (status 1) +++
[pid 4511] +++ exited (status 1) +++
[pid 4510] +++ exited (status 1) +++
[pid 4512] +++ exited (status 1) +++
[pid 4509] +++ exited (status 1) +++
```

**Comment by flx42** [comment] 2017-07-06 16:35
Hello,

Can you share the NVML log? Follow the process indicated in this [comment](https://github.com/NVIDIA/nvidia-docker/issues/206#issuecomment-309856244):
```
sudo -u nvidia-docker env __NVML_DBG_LVL=DEBUG __NVML_DBG_FILE=/tmp/nvml.log /usr/bin/nvidia-docker-plugin -s /var/lib/nvidia-docker
```

Thank you

**Comment by lmatt-bit** [comment] 2017-07-07 01:24
@flx42 , sure, here is the NVML log.  Thanks for your help.

[nvml.log.zip](https://github.com/NVIDIA/nvidia-docker/files/1129676/nvml.log.zip)

**Comment by flx42** [comment] 2017-07-07 01:26
Thanks, I will forward it to the right team. What's the output of `nvidia-smi` on your machine by the way?

**Comment by lmatt-bit** [comment] 2017-07-07 01:26
`
[root@MTAPI ~]# nvidia-smi
Fri Jul  7 09:26:25 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M60           Off  | 0000:00:02.0     Off |                  Off |
| N/A   35C    P0    37W / 150W |      0MiB /  8123MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
`

**Comment by cliffwoolley** [comment] 2017-07-07 01:30
That's interesting... Tesla M60 is a dual-GPU board.  Where is the second
GPU?  Are we running in a VM or other restricted environment here?

**Comment by lmatt-bit** [comment] 2017-07-07 01:39
@cliffwoolley yes, you can think it as a similar product with p2.xlarge(one k80) instance on aws.  But I don't have much details on how it's virtualized or restricted.

**Comment by flx42** [comment] 2017-07-07 01:41
I see, and what's the output of `nvidia-smi -q`?
Also, for good measure, please also share the output of `lspci -d 10de:` (package `pciutils`)

**Comment by lmatt-bit** [comment] 2017-07-07 01:44
nvidia-smi -q

[nvidia-smi-q.txt](https://github.com/NVIDIA/nvidia-docker/files/1129746/nvidia-smi-q.txt)

lspci -d 10de:

> 00:02.0 VGA compatible controller: NVIDIA Corporation Device 13f2 (rev a1)

**Comment by flx42** [comment] 2017-07-07 01:45
Thanks, it seems to be PCIe passthrough:
```
    GPU Virtualization Mode
        Virtualization mode         : Pass-Through
```

**Comment by 3XX0** [comment] 2017-11-14 06:35
Closing, feel free to reopen if you can reproduce with 2.0/master.

**Closed by 3XX0** 2017-11-14 06:35 UTC
