### ISSUE TITLE
Issue with Nvidia in apolloauto docker

### ISSUE THREAD

**Issue by miewan** [NVIDIA/nvidia-docker#1208] opened 2020-03-04 20:29 UTC
I am having problem with Nvdia failed handshake. My pc was reboot and I need to install Clang again in the Apollo Auto docker. This was totally fine yesterday. I can work with Clang without any problem yesterday

I am using Linux Ubuntu 14.04, docker 18.06, and

### Steps to reproduce the issue:

- I run this command 
`shifa@in_dev_docker:/apollo$ sudo bash docker/build/installers/install_clang.sh`

- And the output
`W: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/Packages  gnutls_handshake() failed: Handshake failed

W: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/Packages  gnutls_handshake() failed: Handshake failed

E: Some index files failed to download. They have been ignored, or old ones used instead.
`

Can anyone help me with this. I don't know why this happen when it works fine yesterday

**Comment by RenaudWasTaken** [comment] 2020-03-09 19:50
Hello!

I can't reproduce this, it's possible this is a transient issue. Let me know if this issue is still here.
Closing in the meantime.

**Closed by RenaudWasTaken** 2020-03-09 19:50 UTC
