### ISSUE TITLE
when I used --privileged=true , it show all the device in the container

### ISSUE THREAD

**Issue by yan234280533** [NVIDIA/nvidia-docker#764] opened 2018-06-14 11:36 UTC
### 1. Issue or feature description
when I used --privileged=true , it show all the device in the container

### 2. Steps to reproduce the issue
1.  NV_GPU=1  nvidia-docker run -it --rm --privileged=true  nvidia/cuda
2.  root@2a3b245b81e7:/# nvidia-smi -q | grep UUID
    GPU UUID                        : GPU-03073c9f-999e-eccd-39b4-73c351820dd2
    GPU UUID                        : GPU-7e2911a7-f907-a3bd-da2c-6d4b07556478

it show all the device in the container

my docker version 17.12.1-ce

my nvidia-docker is : nvidia-docker2-2.0.3-1.docker17.12.1.ce.noarch

**Comment by flx42** [comment] 2018-06-18 17:28
Yes, this is by design of the `--privileged` option of Docker, it whitelists all devices. Compare:
```
$ docker run --runtime=nvidia --privileged -ti nvidia/cuda cat /sys/fs/cgroup/devices/devices.list
a *:* rwm
```
And:
```
docker run -ti --runtime=nvidia nvidia/cuda cat /sys/fs/cgroup/devices/devices.list
c 1:5 rwm
c 1:3 rwm
c 1:9 rwm
c 1:8 rwm
c 5:0 rwm
c 5:1 rwm
c *:* m
b *:* m
c 1:7 rwm
c 136:* rwm
c 5:2 rwm
c 10:200 rwm
c 195:255 rw
c 235:0 rw
c 235:1 rw
c 195:1 rw
c 195:0 rw
```

It's unclear to me which option (`--privileged` or `NV_GPU`) should "win".  We have an idea to make `NV_GPU` compatible with `--privileged`, but that will be for a future release.

It's probably better to avoid `--privileged` for now, and instead use capabilities.

**Comment by RenaudWasTaken** [comment] 2019-04-12 07:53
`--privileged` should win, this is the current behavior.
I'll be closing this issue :)

**Closed by RenaudWasTaken** 2019-04-12 07:53 UTC
Labels: enhancement
