### ISSUE TITLE
yum package nvidia-container-runtime-1.1.1-1.docker1.12.6.x86_64 is missing

### ISSUE THREAD

**Issue by jamesatha** [NVIDIA/nvidia-docker#672] opened 2018-03-16 18:20 UTC
### 2. Steps:
```
$ sudo yum install nvidia-container-runtime-1.1.1-1.docker1.12.6
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.ash.fastserv.com
 * epel: mirror.beyondhosting.net
 * extras: repos.mia.quadranet.com
 * updates: repos-va.psychz.net
No package nvidia-container-runtime-1.1.1-1.docker1.12.6 available.
```

### 3. Other info:
I am still running docker 1.12 and cannot upgrade for the time being - other issues in this repo still refer to this package so I hope it hasn't been deprecated completely. I was able to do this in the past and have adding the nvidia-docker repo to my list. I'm guessing it was recently removed. Is there a workaround for now? And will this be added again? I'm hoping its removal was a mistake

**Comment by flx42** [comment] 2018-03-16 18:23
It should still be available: https://github.com/NVIDIA/nvidia-docker/issues/672
Can you try a `sudo yum makecache fast`?

**Comment by jamesatha** [comment] 2018-03-16 18:27
That didn't seem to help. It still said there is no package

``` 
$ cat /etc/yum.repos.d/nvidia-docker.repo
[libnvidia-container]
name=libnvidia-container
baseurl=https://nvidia.github.io/libnvidia-container/centos7/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://nvidia.github.io/libnvidia-container/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt

[nvidia-container-runtime]
name=nvidia-container-runtime
baseurl=https://nvidia.github.io/nvidia-container-runtime/centos7/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://nvidia.github.io/nvidia-container-runtime/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt

[nvidia-docker]
name=nvidia-docker
baseurl=https://nvidia.github.io/nvidia-docker/centos7/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://nvidia.github.io/nvidia-docker/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
```

```
$ sudo yum makecache fast
Loaded plugins: fastestmirror
base                                                                                                                                                       | 3.6 kB  00:00:00     
docker                                                                                                                                                     | 2.9 kB  00:00:00     
epel/x86_64/metalink                                                                                                                                       |  18 kB  00:00:00     
extras                                                                                                                                                     | 3.4 kB  00:00:00     
kubernetes                                                                                                                                                 | 1.4 kB  00:00:00     
libnvidia-container/x86_64/signature                                                                                                                       |  455 B  00:00:00     
libnvidia-container/x86_64/signature                                                                                                                       | 2.0 kB  00:00:00 !!! 
nvidia-container-runtime/x86_64/signature                                                                                                                  |  455 B  00:00:00     
nvidia-container-runtime/x86_64/signature                                                                                                                  | 2.0 kB  00:00:00 !!! 
nvidia-docker/x86_64/signature                                                                                                                             |  455 B  00:00:00     
nvidia-docker/x86_64/signature                                                                                                                             | 2.0 kB  00:00:00 !!! 
updates                                                                                                                                                    | 3.4 kB  00:00:00     
Loading mirror speeds from cached hostfile
 * base: mirror.ash.fastserv.com
 * epel: mirror.beyondhosting.net
 * extras: mirror.sesp.northwestern.edu
 * updates: repos-va.psychz.net
Metadata Cache Created
```
```
$ sudo yum install nvidia-container-runtime-1.1.1-1.docker1.12.6
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.ash.fastserv.com
 * epel: mirror.beyondhosting.net
 * extras: repos.mia.quadranet.com
 * updates: repos-va.psychz.net
No package nvidia-container-runtime-1.1.1-1.docker1.12.6 available.
Error: Nothing to do
```

**Comment by flx42** [comment] 2018-03-16 18:30
What's the output of `yum list nvidia-container-runtime --show-duplicates`?

**Comment by jamesatha** [comment] 2018-03-16 18:32
```$ yum list nvidia-container-runtime --show-duplicates
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.ash.fastserv.com
 * epel: mirror.beyondhosting.net
 * extras: mirror.umd.edu
 * updates: repos-va.psychz.net
Error: No matching Packages to list
```

**Comment by flx42** [comment] 2018-03-16 18:38
You probably have an issue with your configuration, the following dockerfile works fine for me:
```
FROM centos:7

RUN curl -s -L https://nvidia.github.io/nvidia-docker/centos7/x86_64/nvidia-docker.repo | \
    tee /etc/yum.repos.d/nvidia-docker.repo

CMD yum install -y nvidia-container-runtime-1.1.1-1.docker1.12.6
```

**Comment by jamesatha** [comment] 2018-03-16 18:39
I changed my repo but I only see the newer versions:
```$ yum search --showduplicates nvidia-container-runtime
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.ash.fastserv.com
 * epel: mirror.beyondhosting.net
 * extras: mirrors.centos.webair.com
 * updates: mirror.datto.com
===================================================================== N/S matched: nvidia-container-runtime ======================================================================
nvidia-container-runtime-2.0.0-1.docker17.12.1.x86_64 : NVIDIA container runtime
nvidia-container-runtime-hook-1.3.0-1.x86_64 : NVIDIA container runtime hook

  Name and summary matches only, use "search all" for everything.
```

**Comment by flx42** [comment] 2018-03-16 18:46
Is that with the `--show-duplicates`?

**Comment by jamesatha** [comment] 2018-03-16 18:49
Yes, that is with the `--showduplicates`` flag

**Comment by jamesatha** [comment] 2018-03-16 18:55
I used your docker file and it successfully built. But inside the container, it doesn't seem to have the package. I manually started the container and installed the package. And when I did, it ended up with the wrong version:

```[root@0635974a4ba2 /]# yum list installed | grep nvidia
libnvidia-container-tools.x86_64     1.0.0-0.1.beta.1       @libnvidia-container
libnvidia-container1.x86_64          1.0.0-0.1.beta.1       @libnvidia-container
nvidia-container-runtime.x86_64      2.0.0-1.docker17.12.1  @nvidia-container-runtime
nvidia-container-runtime-hook.x86_64 1.3.0-1                @nvidia-container-runtime
```

**Comment by flx42** [comment] 2018-03-16 18:57
The package is installed during the `docker run`, since I used `CMD` and not `RUN`.
What's the output of `docker run` for this Dockerfile?

**Comment by jamesatha** [comment] 2018-03-16 19:05
I switched the `CMD` to `RUN` and it installed during the build when I actually run the container and look at the installed packages, it has the latest, not the version I wanted:
```docker run -it --rm centos_nvidia bash
[root@de9a1e3e6f1a /]# yum list installed | grep nvid
libnvidia-container-tools.x86_64     1.0.0-0.1.beta.1       @libnvidia-container
libnvidia-container1.x86_64          1.0.0-0.1.beta.1       @libnvidia-container
nvidia-container-runtime.x86_64      2.0.0-1.docker17.12.1  @nvidia-container-runtime
nvidia-container-runtime-hook.x86_64 1.3.0-1                @nvidia-container-runtime
```

**Comment by flx42** [comment] 2018-03-16 20:21
Not sure why it's preventing you from installing though. I can't reproduce it.
You also have `nvidia-container-runtime-2.0.0-1.docker1.12.6.x86_64` by the way, try this one.

**Comment by jamesatha** [comment] 2018-03-16 22:59
This is my current workaround. It works in a docker centos7 container and a new centos7 machine in AWS. I'm hoping this helps anyone else who hits this issue.

```
# Source: https://nvidia.github.io/nvidia-container-runtime/
curl -s -L https://nvidia.github.io/nvidia-container-runtime/centos7/nvidia-container-runtime.repo | sudo tee /etc/yum.repos.d/nvidia-container-runtime.repo

# Get the obsoleted package
sudo yum --setopt=obsoletes=0 install -y nvidia-container-runtime-1.1.1-1.docker1.12.6.x86_64
```
I'm not sure how long this will work but it works for me today. I would like to know if there is a more robust and future-proof way to do this. 

I'll look into `nvidia-container-runtime-2.0.0-1.docker1.12.6.x86_64` for future use, thanks.

**Comment by flx42** [comment] 2018-03-19 16:41
This seems weird to me that the Dockerfile doesn't work for you.

**Comment by flx42** [comment] 2018-04-09 17:59
Couldn't reproduce the issue here. closing.

**Closed by flx42** 2018-04-09 17:59 UTC
