### ISSUE TITLE
OCI runtime create failed

### ISSUE THREAD

**Issue by s0r2637** [NVIDIA/nvidia-docker#1538] opened 2021-08-18 04:35 UTC
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_Also, before reporting a new issue, please make sure that:_

- _You read carefully the [documentation and frequently asked questions](https://github.com/NVIDIA/nvidia-docker/wiki)._
- _You [searched](https://github.com/NVIDIA/nvidia-docker/issues?utf8=%E2%9C%93&q=is%3Aissue) for a similar issue and this is not a duplicate of an existing one._
- _This issue is not related to [NGC](https://github.com/NVIDIA/nvidia-docker/wiki/NGC), otherwise, please use the [devtalk forums](https://devtalk.nvidia.com/default/board/200/nvidia-gpu-cloud-ngc-users/) instead._
- _You went through the [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting) steps._

---

### 1. Issue or feature description
getting the following error when running `docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi`
**docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: signal: segmentation fault (core dumped), stdout: , stderr:: unknown.**

### 2. Steps to reproduce the issue
run `docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi`
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] **-- WARNING, the following logs are for debugging purposes only --
I0818 04:27:25.064454 5479 nvc.c:372] initializing library context (version=1.5.0~rc.1, build=5884d4232da9109423f55e79d57df264991c27cf)
I0818 04:27:25.064547 5479 nvc.c:346] using root /
I0818 04:27:25.064559 5479 nvc.c:347] using ldcache /etc/ld.so.cache
I0818 04:27:25.064568 5479 nvc.c:348] using unprivileged user 1000:1000**
 - [ ] Kernel version from `uname -a`
 - [ ] Linux arlsrini-GS66-Stealth-10SFS 5.4.0-81-generic #91~18.04.1-Ubuntu SMP Fri Jul 23 13:36:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - [ ] Any relevant kernel output lines from `dmesg` --  [  187.485237] nvidia-containe[3875]: segfault at 0 ip 00007f018c3afc6a sp 00007ffe23aadcc8 error 4 in libc-2.27.so[7f018c306000+1e7000]
[  187.485240] Code: 0f b6 0e 0f b6 07 29 c8 c3 0f 1f 80 00 00 00 00 89 f8 31 d2 66 0f ef ff 09 f0 25 ff 0f 00 00 3d c0 0f 00 00 0f 8f 78 02 00 00 <f3> 0f 6f 0f f3 0f 6f 06 66 0f 74 c1 66 0f da c1 66 0f ef c9 66 0f
[  187.590761] docker0: port 1(veth5422417) entered disabled state
[  187.591692] device veth5422417 left promiscuous mode
[  187.591694] docker0: port 1(veth5422417) entered disabled state
[  207.785073] snd_hda_codec_hdmi hdaudioC1D0: HDMI: invalid ELD data byte 23
[  249.248140] netlink: 'svpn': attribute type 6 has an invalid length.
[  249.248144] netlink: 'svpn': attribute type 4 has an invalid length.
[  249.248289] netlink: 'svpn': attribute type 6 has an invalid length.
[  249.248291] netlink: 'svpn': attribute type 4 has an invalid length.
[  249.249809] netlink: 'svpn': attribute type 6 has an invalid length.
[  249.249811] netlink: 'svpn': attribute type 4 has an invalid length.
[  249.250558] netlink: 'svpn': attribute type 6 has an invalid length.
[  249.250560] netlink: 'svpn': attribute type 4 has an invalid length.
[  249.251974] netlink: 'svpn': attribute type 6 has an invalid length.
[  249.251975] netlink: 'svpn': attribute type 4 has an invalid length.
[  675.825345] docker0: port 1(veth19b4a6d) entered blocking state
[  675.825346] docker0: port 1(veth19b4a6d) entered disabled state
[  675.825399] device veth19b4a6d entered promiscuous mode
[  675.825469] docker0: port 1(veth19b4a6d) entered blocking state
[  675.825470] docker0: port 1(veth19b4a6d) entered forwarding state
[  675.825636] docker0: port 1(veth19b4a6d) entered disabled state
[  675.921661] nvidia-containe[5429]: segfault at 0 ip 00007fca07fe9c6a sp 00007ffff9ca9428 error 4 in libc-2.27.so[7fca07f40000+1e7000]
[  675.921664] Code: 0f b6 0e 0f b6 07 29 c8 c3 0f 1f 80 00 00 00 00 89 f8 31 d2 66 0f ef ff 09 f0 25 ff 0f 00 00 3d c0 0f 00 00 0f 8f 78 02 00 00 <f3> 0f 6f 0f f3 0f 6f 06 66 0f 74 c1 66 0f da c1 66 0f ef c9 66 0f
[  676.032869] docker0: port 1(veth19b4a6d) entered disabled state
[  676.033942] device veth19b4a6d left promiscuous mode
[  676.033944] docker0: port 1(veth19b4a6d) entered disabled state
[  804.749997] nvidia-containe[5479]: segfault at 0 ip 00007fb3cb334c6a sp 00007ffde42eedd8 error 4 in libc-2.27.so[7fb3cb28b000+1e7000]
[  804.750011] Code: 0f b6 0e 0f b6 07 29 c8 c3 0f 1f 80 00 00 00 00 89 f8 31 d2 66 0f ef ff 09 f0 25 ff 0f 00 00 3d c0 0f 00 00 0f 8f 78 02 00 00 <f3> 0f 6f 0f f3 0f 6f 06 66 0f 74 c1 66 0f da c1 66 0f ef c9 66 0f
 - [ ] Driver information from `nvidia-smi -a` ==============NVSMI LOG==============

Timestamp                                 : Wed Aug 18 00:32:25 2021
Driver Version                            : 460.91.03
CUDA Version                              : 11.2

Attached GPUs                             : 1
GPU 00000000:01:00.0
    Product Name                          : GeForce RTX 2070 Super with Max-Q Design
    Product Brand                         : GeForce
    Display Mode                          : Enabled
    Display Active                        : Enabled
    Persistence Mode                      : Disabled
    MIG Mode
        Current                           : N/A
        Pending                           : N/A
    Accounting Mode                       : Disabled
    Accounting Mode Buffer Size           : 4000
    Driver Model
        Current                           : N/A
        Pending                           : N/A
    Serial Number                         : N/A
    GPU UUID                              : GPU-0f53ac88-f55b-22a7-b221-e09ba6ea7947
    Minor Number                          : 0
    VBIOS Version                         : 90.04.97.00.66
    MultiGPU Board                        : No
    Board ID                              : 0x100
    GPU Part Number                       : N/A
    Inforom Version
        Image Version                     : G001.0000.02.04
        OEM Object                        : 1.1
        ECC Object                        : N/A
        Power Management Object           : N/A
    GPU Operation Mode
        Current                           : N/A
        Pending                           : N/A
    GPU Virtualization Mode
        Virtualization Mode               : None
        Host VGPU Mode                    : N/A
    IBMNPU
        Relaxed Ordering Mode             : N/A
    PCI
        Bus                               : 0x01
        Device                            : 0x00
        Domain                            : 0x0000
        Device Id                         : 0x1E9110DE
        Bus Id                            : 00000000:01:00.0
        Sub System Id                     : 0x12AE1462
        GPU Link Info
            PCIe Generation
                Max                       : 3
                Current                   : 1
            Link Width
                Max                       : 16x
                Current                   : 16x
        Bridge Chip
            Type                          : N/A
            Firmware                      : N/A
        Replays Since Reset               : 0
        Replay Number Rollovers           : 0
        Tx Throughput                     : 1000 KB/s
        Rx Throughput                     : 2000 KB/s
    Fan Speed                             : N/A
    Performance State                     : P8
    Clocks Throttle Reasons
        Idle                              : Active
        Applications Clocks Setting       : Not Active
        SW Power Cap                      : Not Active
        HW Slowdown                       : Not Active
            HW Thermal Slowdown           : Not Active
            HW Power Brake Slowdown       : Not Active
        Sync Boost                        : Not Active
        SW Thermal Slowdown               : Not Active
        Display Clock Setting             : Not Active
    FB Memory Usage
        Total                             : 7982 MiB
        Used                              : 285 MiB
        Free                              : 7697 MiB
    BAR1 Memory Usage
        Total                             : 256 MiB
        Used                              : 6 MiB
        Free                              : 250 MiB
    Compute Mode                          : Default
    Utilization
        Gpu                               : 2 %
        Memory                            : 4 %
        Encoder                           : 0 %
        Decoder                           : 0 %
    Encoder Stats
        Active Sessions                   : 0
        Average FPS                       : 0
        Average Latency                   : 0
    FBC Stats
        Active Sessions                   : 0
        Average FPS                       : 0
        Average Latency                   : 0
    Ecc Mode
        Current                           : N/A
        Pending                           : N/A
    ECC Errors
        Volatile
            SRAM Correctable              : N/A
            SRAM Uncorrectable            : N/A
            DRAM Correctable              : N/A
            DRAM Uncorrectable            : N/A
        Aggregate
            SRAM Correctable              : N/A
            SRAM Uncorrectable            : N/A
            DRAM Correctable              : N/A
            DRAM Uncorrectable            : N/A
    Retired Pages
        Single Bit ECC                    : N/A
        Double Bit ECC                    : N/A
        Pending Page Blacklist            : N/A
    Remapped Rows                         : N/A
    Temperature
        GPU Current Temp                  : 41 C
        GPU Shutdown Temp                 : 100 C
        GPU Slowdown Temp                 : 95 C
        GPU Max Operating Temp            : 87 C
        GPU Target Temperature            : N/A
        Memory Current Temp               : N/A
        Memory Max Operating Temp         : N/A
    Power Readings
        Power Management                  : N/A
        Power Draw                        : 13.36 W
        Power Limit                       : N/A
        Default Power Limit               : N/A
        Enforced Power Limit              : N/A
        Min Power Limit                   : N/A
        Max Power Limit                   : N/A
    Clocks
        Graphics                          : 300 MHz
        SM                                : 300 MHz
        Memory                            : 405 MHz
        Video                             : 540 MHz
    Applications Clocks
        Graphics                          : N/A
        Memory                            : N/A
    Default Applications Clocks
        Graphics                          : N/A
        Memory                            : N/A
    Max Clocks
        Graphics                          : 2100 MHz
        SM                                : 2100 MHz
        Memory                            : 5501 MHz
        Video                             : 1950 MHz
    Max Customer Boost Clocks
        Graphics                          : N/A
    Clock Policy
        Auto Boost                        : N/A
        Auto Boost Default                : N/A
    Processes
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 1540
            Type                          : G
            Name                          : /usr/lib/xorg/Xorg
            Used GPU Memory               : 188 MiB
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 2506
            Type                          : G
            Name                          : /usr/bin/gnome-shell
            Used GPU Memory               : 60 MiB
        GPU instance ID                   : N/A
        Compute instance ID               : N/A
        Process ID                        : 3954
            Type                          : G
            Name                          : /opt/google/chrome/chrome --type=gpu-process --field-trial-handle=1317606111866444597,2767894209968594177,131072 --enable-crashpad --crashpad-handler-pid=3916 --enable-crash-reporter=c0dde21b-7e11-4710-92b0-ce915812382b, --gpu-preferences=UAAAAAAAAAAgAAAQAAAAAAAAAAAAAAAAAABgAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAABgAAAAAAAAAGAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAA= --shared-files
            Used GPU Memory               : 32 MiB

 - [ ] Docker version from `docker version` Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:08 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:16 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'` or_: command not found
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                    Version                  Architecture             Description
+++-=======================================-========================-========================-====================================================================================
un  libgldispatch0-nvidia                   <none>                   <none>                   (no description available)
ii  libnvidia-cfg1-460:amd64                460.91.03-0ubuntu0.18.04 amd64                    NVIDIA binary OpenGL/GLX configuration library
un  libnvidia-cfg1-any                      <none>                   <none>                   (no description available)
un  libnvidia-common                        <none>                   <none>                   (no description available)
ii  libnvidia-common-460                    460.91.03-0ubuntu0.18.04 all                      Shared files used by the NVIDIA libraries
un  libnvidia-compute                       <none>                   <none>                   (no description available)
rc  libnvidia-compute-450-server:amd64      450.102.04-0ubuntu0.18.0 amd64                    NVIDIA libcompute package
ii  libnvidia-compute-460:amd64             460.91.03-0ubuntu0.18.04 amd64                    NVIDIA libcompute package
ii  libnvidia-compute-460:i386              460.91.03-0ubuntu0.18.04 i386                     NVIDIA libcompute package
rc  libnvidia-compute-460-server:amd64      460.91.03-0ubuntu0.18.04 amd64                    NVIDIA libcompute package
rc  libnvidia-compute-470:amd64             470.57.02-0ubuntu0.18.04 amd64                    NVIDIA libcompute package
ii  libnvidia-container-tools               1.5.0~rc.1-1             amd64                    NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64              1.5.0~rc.1-1             amd64                    NVIDIA container runtime library
un  libnvidia-decode                        <none>                   <none>                   (no description available)
ii  libnvidia-decode-460:amd64              460.91.03-0ubuntu0.18.04 amd64                    NVIDIA Video Decoding runtime libraries
ii  libnvidia-decode-460:i386               460.91.03-0ubuntu0.18.04 i386                     NVIDIA Video Decoding runtime libraries
un  libnvidia-encode                        <none>                   <none>                   (no description available)
ii  libnvidia-encode-460:amd64              460.91.03-0ubuntu0.18.04 amd64                    NVENC Video Encoding runtime library
ii  libnvidia-encode-460:i386               460.91.03-0ubuntu0.18.04 i386                     NVENC Video Encoding runtime library
un  libnvidia-extra                         <none>                   <none>                   (no description available)
ii  libnvidia-extra-460:amd64               460.91.03-0ubuntu0.18.04 amd64                    Extra libraries for the NVIDIA driver
un  libnvidia-fbc1                          <none>                   <none>                   (no description available)
ii  libnvidia-fbc1-460:amd64                460.91.03-0ubuntu0.18.04 amd64                    NVIDIA OpenGL-based Framebuffer Capture runtime library
ii  libnvidia-fbc1-460:i386                 460.91.03-0ubuntu0.18.04 i386                     NVIDIA OpenGL-based Framebuffer Capture runtime library
un  libnvidia-gl                            <none>                   <none>                   (no description available)
ii  libnvidia-gl-460:amd64                  460.91.03-0ubuntu0.18.04 amd64                    NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
ii  libnvidia-gl-460:i386                   460.91.03-0ubuntu0.18.04 i386                     NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
un  libnvidia-ifr1                          <none>                   <none>                   (no description available)
ii  libnvidia-ifr1-460:amd64                460.91.03-0ubuntu0.18.04 amd64                    NVIDIA OpenGL-based Inband Frame Readback runtime library
ii  libnvidia-ifr1-460:i386                 460.91.03-0ubuntu0.18.04 i386                     NVIDIA OpenGL-based Inband Frame Readback runtime library
un  libnvidia-ml1                           <none>                   <none>                   (no description available)
rc  linux-objects-nvidia-470-5.4.0-81-gener 5.4.0-81.91~18.04.1      amd64                    Linux kernel nvidia modules for version 5.4.0-81 (objects)
un  nvidia-304                              <none>                   <none>                   (no description available)
un  nvidia-340                              <none>                   <none>                   (no description available)
un  nvidia-384                              <none>                   <none>                   (no description available)
un  nvidia-390                              <none>                   <none>                   (no description available)
un  nvidia-common                           <none>                   <none>                   (no description available)
un  nvidia-compute-utils                    <none>                   <none>                   (no description available)
ii  nvidia-compute-utils-460                460.91.03-0ubuntu0.18.04 amd64                    NVIDIA compute utilities
ii  nvidia-container-runtime                3.5.0-1                  amd64                    NVIDIA container runtime
un  nvidia-container-runtime-hook           <none>                   <none>                   (no description available)
ii  nvidia-container-toolkit                1.6.0~rc.1-1             amd64                    NVIDIA container runtime hook
ii  nvidia-dkms-460                         460.91.03-0ubuntu0.18.04 amd64                    NVIDIA DKMS package
un  nvidia-dkms-kernel                      <none>                   <none>                   (no description available)
un  nvidia-docker                           <none>                   <none>                   (no description available)
ii  nvidia-docker2                          2.6.0-1                  all                      nvidia-docker CLI wrapper
ii  nvidia-driver-450                       460.91.03-0ubuntu0.18.04 amd64                    Transitional package for nvidia-driver-460
ii  nvidia-driver-460                       460.91.03-0ubuntu0.18.04 amd64                    NVIDIA driver metapackage
un  nvidia-driver-binary                    <none>                   <none>                   (no description available)
un  nvidia-kernel-common                    <none>                   <none>                   (no description available)
ii  nvidia-kernel-common-460                460.91.03-0ubuntu0.18.04 amd64                    Shared files used with the kernel module
un  nvidia-kernel-source                    <none>                   <none>                   (no description available)
ii  nvidia-kernel-source-460                460.91.03-0ubuntu0.18.04 amd64                    NVIDIA kernel source package
un  nvidia-legacy-304xx-vdpau-driver        <none>                   <none>                   (no description available)
un  nvidia-legacy-340xx-vdpau-driver        <none>                   <none>                   (no description available)
un  nvidia-libopencl1-dev                   <none>                   <none>                   (no description available)
un  nvidia-opencl-icd                       <none>                   <none>                   (no description available)
un  nvidia-persistenced                     <none>                   <none>                   (no description available)
ii  nvidia-prime                            0.8.16~0.18.04.1         all                      Tools to enable NVIDIA's Prime
ii  nvidia-settings                         470.57.01-0ubuntu0.18.04 amd64                    Tool for configuring the NVIDIA graphics driver
un  nvidia-settings-binary                  <none>                   <none>                   (no description available)
un  nvidia-smi                              <none>                   <none>                   (no description available)
un  nvidia-utils                            <none>                   <none>                   (no description available)
ii  nvidia-utils-460                        460.91.03-0ubuntu0.18.04 amd64                    NVIDIA driver support binaries
un  nvidia-vdpau-driver                     <none>                   <none>                   (no description available)
ii  xserver-xorg-video-nvidia-460           460.91.03-0ubuntu0.18.04 amd64                    NVIDIA binary Xorg driver
dpkg-query: no packages found matching *nvidia*rpm
dpkg-query: no packages found matching -qa
 - [ ] NVIDIA container library version from `nvidia-container-cli -V` version: 1.5.0~rc.1
build date: 2021-08-13T09:32+00:00
build revision: 5884d4232da9109423f55e79d57df264991c27cf
build compiler: x86_64-linux-gnu-gcc-7 7.5.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used
docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi

**Comment by elezar** [comment] 2021-08-18 07:44
Hi. This is a duplicate of #1533. There is a bug in `libnvidia-container` `1.5.0~rc.1` that was published to the experimental repositories. The package has since been removed from the repos and a fix will be included in the `1.5.0~rc.2` version that is being released soon.

**Closed** 2021-08-18 07:44 UTC
