### ISSUE TITLE
Unable to install git in centos cuda images under nvidia runtime

### ISSUE THREAD

**Issue by borispf** [NVIDIA/nvidia-docker#562] opened 2017-12-05 16:51 UTC
### 1. Issue or feature description
Unable to install git using yum under the nvidia/cuda:9.0-base-centos7 image when using the nvidia runtime.

### 2. Steps to reproduce the issue
```
$ docker run --runtime=nvidia --rm nvidia/cuda:9.0-base-centos7 bash -c "yum install -y git"
<snip>
  Installing : git-1.8.3.1-12.el7_4.x86_64                                40/40 
error: unpacking of archive failed on file /usr/bin/git;5a26cdec: cpio: link
<snip>
Failed:
  git.x86_64 0:1.8.3.1-12.el7_4                                                 

Complete!
```

This works fine:

    docker run --runtime=runc --rm nvidia/cuda:9.0-base-centos7 bash -c "yum install -y git"

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] Kernel version from `uname -a`
```
Linux <hostname omitted> 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
 - [ ] Any relevant kernel output lines from `dmesg`
No idea what would be relevant.
 - [x] Driver information from `nvidia-smi -a`
```
==============NVSMI LOG==============

Timestamp                           : Tue Dec  5 17:32:50 2017
Driver Version                      : 384.81

Attached GPUs                       : 1
GPU 00000000:03:00.0
    Product Name                    : Tesla P100-PCIE-16GB
    Product Brand                   : Tesla

<snip>
```
 - [x] Docker version from `docker version`
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
 - [x] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
```
nvidia-docker2-2.0.1-1.docker17.09.0.ce.noarch
nvidia-kmod-384.81-2.el7.x86_64
xorg-x11-drv-nvidia-devel-384.81-1.el7.x86_64
libnvidia-container1-1.0.0-0.1.alpha.2.x86_64
nvidia-container-runtime-1.1.0-1.docker17.09.0.x86_64
xorg-x11-drv-nvidia-384.81-1.el7.x86_64
xorg-x11-drv-nvidia-gl-384.81-1.el7.x86_64
libnvidia-container-tools-1.0.0-0.1.alpha.2.x86_64
xorg-x11-drv-nvidia-libs-384.81-1.el7.x86_64
```
 - [x] NVIDIA container library version from `nvidia-container-cli -V`
```
version: 1.0.0
build date: 2017-10-31T00:28+0000
build revision: ec15c7233bd2de821ad5127cb0de6b52d9d2083c
build compiler: gcc 4.8.5 20150623 (Red Hat 4.8.5-16)
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections
```
 - [x] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

[nvidia-container-runtime-hook.log](https://github.com/NVIDIA/nvidia-docker/files/1532053/nvidia-container-runtime-hook.log)

 - [ ] Docker command, image and tag used
See above.

**Comment by flx42** [comment] 2017-12-05 17:52
I have a CentOS 7 machine with similar specs. I can reproduce this issue with the `overlay` storage driver on a `xfs` backing filesystem. Is this what you have too? I don't think this combination is really recommended, but we'll still take a look.
`btrfs` on `btrfs` works fine, I didn't try `devicemapper`.

**Comment by borispf** [comment] 2017-12-05 18:07
Thanks for taking a look.
> I can reproduce this issue with the overlay storage driver on a xfs backing filesystem. Is this what you have too?

Yes, that's exactly what I have.

As far I as can tell `overlay` was the default during my setup. I saw that it's not recommended and that `overlay2` should be used but I assumed since it was still the docker default there wouldn't be any major problems. If switching to overlay2 or devicemapper resolves the issue then that works for me, switching my system to `btrfs` is unfortunately beyond my knowledge atm.

**Comment by flx42** [comment] 2017-12-05 18:21
I don't think the CentOS 7 kernel can handle the overlay2 storage driver.
Using a different storage driver might workaround the problem, but it looks like it's a genuine bug from libnvidia-container, nice catch! More details below.

Regarding `btrfs`, you don't need to switch your whole system. You can have a `btrfs` partition mounted at `/var/lib/docker`). In my case I actually have a separate SSD with a single `btrfs` partition.

Ok, regarding the bug. I see the following:
```sh
$ strace -f rpm -i git-1.8.3.1-12.el7_4.x86_64.rpm
[...]
link("/usr/libexec/git-core/git-write-tree;5a26e0fd", "/usr/bin/git;5a26e0fd") = -1 EXDEV (Invalid cross-device link)                                                       
link("/usr/libexec/git-core/git-write-tree;5a26e0fd", "/usr/bin/git-receive-pack;5a26e0fd") = -1 EXDEV (Invalid cross-device link)                                          
link("/usr/libexec/git-core/git-write-tree;5a26e0fd", "/usr/bin/git-upload-archive;5a26e0fd") = -1 EXDEV (Invalid cross-device link)
[...]
```
It makes sense, `overlay` works by creating hard links:
https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/

Which mean we can use a simpler repro:
```sh
$ docker run --runtime=runc -ti nvidia/cuda:9.0-base ln /usr/bin/find /usr/myfind
$ echo $?
0
$ docker run --runtime=nvidia -ti nvidia/cuda:9.0-base ln /usr/bin/find /usr/myfind
ln: failed to create hard link '/usr/myfind' => '/usr/bin/find': Invalid cross-device link
$ docker run --runtime=nvidia -ti nvidia/cuda:9.0-base findmnt
TARGET                                          SOURCE              FSTYPE  OPTIONS
/                                               overlay             overlay rw,rela
|-/proc                                         proc                proc    rw,nosu
| |-/proc/asound                                proc[/asound]       proc    ro,rela
| |-/proc/bus                                   proc[/bus]          proc    ro,rela
| |-/proc/fs                                    proc[/fs]           proc    ro,rela
| |-/proc/irq                                   proc[/irq]          proc    ro,rela
| |-/proc/sys                                   proc[/sys]          proc    ro,rela
| |-/proc/sysrq-trigger                         proc[/sysrq-trigger]
| |                                                                 proc    ro,rela
| |-/proc/kcore                                 tmpfs[/null]        tmpfs   rw,nosu
| |-/proc/timer_list                            tmpfs[/null]        tmpfs   rw,nosu
| |-/proc/timer_stats                           tmpfs[/null]        tmpfs   rw,nosu
| |-/proc/sched_debug                           tmpfs[/null]        tmpfs   rw,nosu
| `-/proc/driver/nvidia                         tmpfs               tmpfs   rw,nosu
|   |-/proc/driver/nvidia/gpus/0000:01:00.0     proc[/driver/nvidia/gpus/0000:01:00.0]
|   |                                                               proc    ro,nosu
|   `-/proc/driver/nvidia/gpus/0000:02:00.0     proc[/driver/nvidia/gpus/0000:02:00.0]
|                                                                   proc    ro,nosu
|-/dev                                          tmpfs               tmpfs   rw,nosu
| |-/dev/console                                devpts[/0]          devpts  rw,nosu
| |-/dev/pts                                    devpts              devpts  rw,nosu
| |-/dev/mqueue                                 mqueue              mqueue  rw,nosu
| |-/dev/shm                                    shm                 tmpfs   rw,nosu
| |-/dev/nvidiactl                              udev[/nvidiactl]    devtmpf ro,nosu
| |-/dev/nvidia-uvm                             udev[/nvidia-uvm]   devtmpf ro,nosu
| |-/dev/nvidia-uvm-tools                       udev[/nvidia-uvm-tools]
| |                                                                 devtmpf ro,nosu
| |-/dev/nvidia1                                udev[/nvidia1]      devtmpf ro,nosu
| `-/dev/nvidia0                                udev[/nvidia0]      devtmpf ro,nosu
|-/sys                                          sysfs               sysfs   ro,nosu
| |-/sys/firmware                               tmpfs               tmpfs   ro,rela
| `-/sys/fs/cgroup                              tmpfs               tmpfs   ro,nosu
|   |-/sys/fs/cgroup/systemd                    cgroup[/docker/163bcf85c274d4c4f95fa418a7d3348e9623a64b0e3b78218f9595e6ea3f884d]
|   |                                                               cgroup  ro,nosu
|   |-/sys/fs/cgroup/perf_event                 cgroup[/docker/163bcf85c274d4c4f95fa418a7d3348e9623a64b0e3b78218f9595e6ea3f884d]
|   |                                                               cgroup  ro,nosu
|   |-/sys/fs/cgroup/pids                       cgroup[/docker/163bcf85c274d4c4f95fa418a7d3348e9623a64b0e3b78218f9595e6ea3f884d]
|   |                                                               cgroup  ro,nosu
|   |-/sys/fs/cgroup/cpu,cpuacct                cgroup[/docker/163bcf85c274d4c4f95fa418a7d3348e9623a64b0e3b78218f9595e6ea3f884d]
|   |                                                               cgroup  ro,nosu
|   |-/sys/fs/cgroup/net_cls,net_prio           cgroup[/docker/163bcf85c274d4c4f95fa418a7d3348e9623a64b0e3b78218f9595e6ea3f884d]
|   |                                                               cgroup  ro,nosu
|   |-/sys/fs/cgroup/devices                    cgroup[/docker/163bcf85c274d4c4f95fa418a7d3348e9623a64b0e3b78218f9595e6ea3f884d]
|   |                                                               cgroup  ro,nosu
|   |-/sys/fs/cgroup/hugetlb                    cgroup[/docker/163bcf85c274d4c4f95fa418a7d3348e9623a64b0e3b78218f9595e6ea3f884d]
|   |                                                               cgroup  ro,nosu
|   |-/sys/fs/cgroup/cpuset                     cgroup[/docker/163bcf85c274d4c4f95fa418a7d3348e9623a64b0e3b78218f9595e6ea3f884d]
|   |                                                               cgroup  ro,nosu
|   |-/sys/fs/cgroup/freezer                    cgroup[/docker/163bcf85c274d4c4f95fa418a7d3348e9623a64b0e3b78218f9595e6ea3f884d]
|   |                                                               cgroup  ro,nosu
|   |-/sys/fs/cgroup/memory                     cgroup[/docker/163bcf85c274d4c4f95fa418a7d3348e9623a64b0e3b78218f9595e6ea3f884d]
|   |                                                               cgroup  ro,nosu
|   `-/sys/fs/cgroup/blkio                      cgroup[/docker/163bcf85c274d4c4f95fa418a7d3348e9623a64b0e3b78218f9595e6ea3f884d]
|                                                                   cgroup  ro,nosu
|-/etc/resolv.conf                              /dev/sda1[/containers/163bcf85c274d4c4f95fa418a7d3348e9623a64b0e3b78218f9595e6ea3f884d/resolv.conf]
|                                                                   ext4    rw,rela
|-/etc/hostname                                 /dev/sda1[/containers/163bcf85c274d4c4f95fa418a7d3348e9623a64b0e3b78218f9595e6ea3f884d/hostname]
|                                                                   ext4    rw,rela
|-/etc/hosts                                    /dev/sda1[/containers/163bcf85c274d4c4f95fa418a7d3348e9623a64b0e3b78218f9595e6ea3f884d/hosts]
|                                                                   ext4    rw,rela
|-/usr/bin                                      overlay[/usr/bin]   overlay rw,rela
| |-/usr/bin/nvidia-smi                         /dev/sdb1[/usr/lib/nvidia-384/bin/nvidia-smi]
| |                                                                 ext4    ro,nosu
| |-/usr/bin/nvidia-debugdump                   /dev/sdb1[/usr/lib/nvidia-384/bin/nvidia-debugdump]
| |                                                                 ext4    ro,nosu
| |-/usr/bin/nvidia-persistenced                /dev/sdb1[/usr/lib/nvidia-384/bin/nvidia-persistenced]
| |                                                                 ext4    ro,nosu
| |-/usr/bin/nvidia-cuda-mps-control            /dev/sdb1[/usr/lib/nvidia-384/bin/nvidia-cuda-mps-control]
| |                                                                 ext4    ro,nosu
| `-/usr/bin/nvidia-cuda-mps-server             /dev/sdb1[/usr/lib/nvidia-384/bin/nvidia-cuda-mps-server]
|                                                                   ext4    ro,nosu
|-/usr/lib/x86_64-linux-gnu                     overlay[/usr/lib/x86_64-linux-gnu]
|                                                                   overlay rw,rela
| |-/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.384.90
| |                                             /dev/sdb1[/usr/lib/nvidia-384/libnvidia-ml.so.384.90]
| |                                                                 ext4    ro,nosu
| |-/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.384.90
| |                                             /dev/sdb1[/usr/lib/nvidia-384/libnvidia-cfg.so.384.90]
| |                                                                 ext4    ro,nosu
| |-/usr/lib/x86_64-linux-gnu/libcuda.so.384.90 /dev/sdb1[/usr/lib/x86_64-linux-gnu/libcuda.so.384.90]
| |                                                                 ext4    ro,nosu
| |-/usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.384.90
| |                                             /dev/sdb1[/usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.384.90]
| |                                                                 ext4    ro,nosu
| |-/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.384.90
| |                                             /dev/sdb1[/usr/lib/nvidia-384/libnvidia-ptxjitcompiler.so.384.90]
| |                                                                 ext4    ro,nosu
| |-/usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.384.90
| |                                             /dev/sdb1[/usr/lib/nvidia-384/libnvidia-fatbinaryloader.so.384.90]
| |                                                                 ext4    ro,nosu
| `-/usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.384.90
|                                               /dev/sdb1[/usr/lib/nvidia-384/libnvidia-compiler.so.384.90]
|                                                                   ext4    ro,nosu
`-/run/nvidia-persistenced/socket               tmpfs[/nvidia-persistenced/socket]
                                                                    tmpfs   rw,nosu
```

**Comment by flx42** [comment] 2017-12-20 18:27
Closing this one, it has been fixed in https://github.com/NVIDIA/libnvidia-container/commit/584bca59ecd7e67011b83d90cc5ac07db35dd47c
You will have to wait until we do a new release of `libnvidia-container` though.

**Closed by flx42** 2017-12-20 18:27 UTC

**Comment by borispf** [comment] 2017-12-21 21:04
Thanks for the quick turnaround!
