### ISSUE TITLE
unsupported Docker version (with new docker version v17.03.0-ce)

### ISSUE THREAD

**Issue by JoBlo777** [NVIDIA/nvidia-docker#324] opened 2017-03-02 15:52 UTC
Hello 

after upgrading to docker v17.03.0.ce I get the message 

nvidia-docker | 2017/03/02 16:51:26 Error: unsupported Docker version

Can you please help me. 

Thank You

Rupert

**Comment by ThePhen** [comment] 2017-03-02 19:18
:+1:

**Comment by flx42** [comment] 2017-03-02 19:20
Duplicate of #323, we will fix it soon.

**Comment by flx42** [comment] 2017-03-02 19:21
See #323. Will be fixed soon!

**Closed by flx42** 2017-03-02 19:20 UTC
Labels: duplicate
