### ISSUE TITLE
nvidia-docker-plugin exits with "Error: nvml: Unknown Error" - GTX 690

### ISSUE THREAD

**Issue by JonGerrand** [NVIDIA/nvidia-docker#206] opened 2016-09-23 16:03 UTC
Hi there, when running nvidia-docker-plugin locally I get the following output: 

```
$ sudo -u nvidia-docker nvidia-docker-plugin -s /var/lib/nvidia-docker
nvidia-docker-plugin | 2016/09/23 17:48:56 Loading NVIDIA unified memory
nvidia-docker-plugin | 2016/09/23 17:48:56 Loading NVIDIA management library
nvidia-docker-plugin | 2016/09/23 17:48:56 Discovering GPU devices
nvidia-docker-plugin | 2016/09/23 17:48:56 Error: nvml: Unknown Error
```

This is after a fresh install of Ubuntu 14.04 with CUDA V7.5.17 and its packaged driver:

```
$ uname -r
4.2.0-27-generic
```

The `./deviceQuery` and `./bandwidthTest` from the CUDA Samples both pass. 

The output from `nvidia-smi` is as follows:

```
Fri Sep 23 17:55:06 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 690     Off  | 0000:06:00.0     N/A |                  N/A |
| 30%   36C    P8    N/A /  N/A |    147MiB /  2038MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 690     Off  | 0000:07:00.0     N/A |                  N/A |
| 30%   34C    P8    N/A /  N/A |      8MiB /  2047MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
|    1                  Not Supported                                         |
+-----------------------------------------------------------------------------+
```

**Comment by 3XX0** [comment] 2016-09-23 17:22
What about `nvidia-smi -q` on your host?

**Comment by JonGerrand** [comment] 2016-09-26 11:25
Sorry for the delayed response. 

I've attached the output: 
[GTX 690 nvidia-smi -q.txt](https://github.com/NVIDIA/nvidia-docker/files/492945/GTX.690.nvidia-smi.-q.txt)

**Comment by 3XX0** [comment] 2016-09-29 09:01
This is odd, does `dmesg` show anything interesting when the error occurs?

**Comment by lxh-123** [comment] 2016-11-02 00:50
I have faced the same problem. Could you show me your final solution？ Thank you in advance！（gtx 690 - caffe）@JonGerrand

**Comment by JonGerrand** [comment] 2016-11-10 13:16
Unfortunately there is no current solution. Using Nvidia-docker was one of several implementations I tried at the research facility I work at while working on a project. 

The machine has been modified (CUDA 8.0 installed with 367.57 driver, 2x Tesla K20c included), but the same identified problem persists.

OS: 14.04.1-Ubuntu

```
$uname -r
4.2.0-27-generic
```
Nvidia-smi output:
```
Thu Nov 10 15:00:13 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K20c          Off  | 0000:01:00.0     Off |                  Off |
| 30%   32C    P8    16W / 225W |      0MiB /  5060MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K20c          Off  | 0000:02:00.0     Off |                  Off |
| 30%   34C    P8    15W / 225W |      0MiB /  5060MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 690     Off  | 0000:06:00.0     N/A |                  N/A |
| 30%   31C    P8    N/A /  N/A |    260MiB /  1990MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 690     Off  | 0000:07:00.0     N/A |                  N/A |
| 30%   30C    P8    N/A /  N/A |      1MiB /  1998MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    2                  Not Supported                                         |
|    3                  Not Supported                                         |
+-----------------------------------------------------------------------------+
```
When running `sudo nvidia-docker-plugin`, on the host, the output is:
```
nvidia-docker-plugin | 2016/11/10 15:02:37 Loading NVIDIA unified memory
nvidia-docker-plugin | 2016/11/10 15:02:37 Loading NVIDIA management library
nvidia-docker-plugin | 2016/11/10 15:02:37 Discovering GPU devices
nvidia-docker-plugin | 2016/11/10 15:02:38 Error: nvml: Unknown Error
```

@3XX0 :  The result of `dmesg | grep -i nvidia` produces: 

```
...
[   14.289047] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  367.57  Mon Oct  3 20:37:01 PDT 2016
[   14.296717] nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  367.57  Mon Oct  3 20:32:57 PDT 2016
[   14.309688] [drm] [nvidia-drm] [GPU ID 0x00000200] Loading driver
[   14.309757] [drm] [nvidia-drm] [GPU ID 0x00000100] Loading driver
[   14.309833] [drm] [nvidia-drm] [GPU ID 0x00000600] Loading driver
[   14.309898] [drm] [nvidia-drm] [GPU ID 0x00000700] Loading driver
[   14.318736] nvidia-uvm: Loaded the UVM driver in 8 mode, major device number 242
[   14.320047] systemd-udevd[1107]: failed to execute '/bin/systemctl' '/bin/systemctl start --no-block nvidia-persistenced.service': No such file or directory
[   16.498289] NVRM: on the primary VGA device. The NVIDIA Linux graphics driver
[   17.340239] systemd-udevd[1129]: failed to execute '/bin/systemctl' '/bin/systemctl stop --no-block nvidia-persistenced': No such file or directory
[   20.104861] init: nvidia-prime main process (1534) terminated with status 127
[   28.114022] nvidia-modeset: Allocated GPU:0 (GPU-634a43dc-ef39-e56b-8b56-1c8dd100e691) @ PCI:0000:06:00.0
[   28.234498] nvidia-modeset: Allocated GPU:1 (GPU-e5686685-fc8a-b347-8766-174c36ac478f) @ PCI:0000:02:00.0
[   28.234805] nvidia-modeset: Freed GPU:1 (GPU-e5686685-fc8a-b347-8766-174c36ac478f) @ PCI:0000:02:00.0
[   28.237899] nvidia-modeset: Allocated GPU:1 (GPU-d9392ad2-4262-a896-07bb-e5c433431334) @ PCI:0000:01:00.0
[   28.238205] nvidia-modeset: Freed GPU:1 (GPU-d9392ad2-4262-a896-07bb-e5c433431334) @ PCI:0000:01:00.0
[   28.241640] nvidia-modeset: Allocated GPU:1 (GPU-0a8b4cc5-96ab-6215-ed94-170cdbd7f227) @ PCI:0000:07:00.0
[ 5303.335771] init: nvidia-docker main process (8483) terminated with status 1
[ 5303.335779] init: nvidia-docker main process ended, respawning
[ 5304.219835] init: nvidia-docker main process (8505) terminated with status 1
[ 5304.219860] init: nvidia-docker main process ended, respawning
[ 5305.120728] init: nvidia-docker main process (8522) terminated with status 1
[ 5305.120749] init: nvidia-docker main process ended, respawning
[ 5306.003044] init: nvidia-docker main process (8540) terminated with status 1
[ 5306.003069] init: nvidia-docker main process ended, respawning
[ 5306.890722] init: nvidia-docker main process (8557) terminated with status 1
[ 5306.890740] init: nvidia-docker main process ended, respawning
[ 5307.770838] init: nvidia-docker main process (8575) terminated with status 1
[ 5307.770845] init: nvidia-docker respawning too fast, stopped
```

**Comment by flx42** [comment] 2016-11-10 23:53
@JonGerrand: sorry, but we're getting out of ideas here. Can you try the following, it should give us a stack trace in the `nvidia-docker` log: `NV_DEBUG=1 nvidia-docker-plugin`

Also, can you remove the 690 cards and try? Or test on another machine with different GPUs.
Thank you

**Comment by JonGerrand** [comment] 2016-11-11 08:04
First things first. Here's the output from `NV_DEBUG=1 nvidia-docker-plugin`:

```
nvidia-docker-plugin | 2016/11/11 09:25:32 Loading NVIDIA unified memory
nvidia-docker-plugin | 2016/11/11 09:25:32 Loading NVIDIA management library
nvidia-docker-plugin | 2016/11/11 09:25:32 Discovering GPU devices
nvidia-docker-plugin | 2016/11/11 09:25:33 Error: nvml: Unknown Error
nvidia-docker-plugin | 2016/11/11 09:25:33 /go/src/github.com/NVIDIA/nvidia-docker/tools/src/nvidia-docker-plugin/main.go:48 (0x404790)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x468a3e)
/usr/local/go/src/runtime/panic.go:423 (0x4388f9)
/usr/local/go/src/log/log.go:334 (0x48bcb1)
/go/src/github.com/NVIDIA/nvidia-docker/tools/src/nvidia-docker-plugin/main.go:38 (0x40461a)
/go/src/github.com/NVIDIA/nvidia-docker/tools/src/nvidia-docker-plugin/main.go:75 (0x404e0c)
/usr/local/go/src/runtime/proc.go:111 (0x43ade0)
/usr/local/go/src/runtime/asm_amd64.s:1721 (0x46ad91)
```
I'm reluctant to remove the 690 card as the workstation is already accepting jobs in our lab. However, as you imply, the GTX 690 might be the culprit here as there seems to be a common problem as raised by @lxh-123. I'll change the issue heading and see if there is any more confirmation provided by the community. 

The plugin works on my personal machine which has the same software configuration, running a single GTX 1080:

OS: 14.04.1-Ubuntu
Kernel: 4.2.0-27-generic
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:05:00.0      On |                  N/A |
| 24%   47C    P8     8W / 180W |    256MiB /  8105MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     14162    G   /usr/bin/X                                     203MiB |
|    0     15237    G   compiz                                          50MiB |
+-----------------------------------------------------------------------------+

```

**Comment by igorbb** [comment] 2016-11-14 15:14
I can confirm I am also getting the same error with a fresh ubuntu 16.04 install


```
Mon Nov 14 16:12:20 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 690     Off  | 0000:04:00.0     N/A |                  N/A |
| 30%   42C    P8    N/A /  N/A |    515MiB /  1995MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 690     Off  | 0000:05:00.0     N/A |                  N/A |
| 30%   40C    P8    N/A /  N/A |    519MiB /  1998MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
|    1                  Not Supported                                         |
+-----------------------------------------------------------------------------+

```


```
==============NVSMI LOG==============

Timestamp                           : Mon Nov 14 16:13:48 2016
Driver Version                      : 367.57

Attached GPUs                       : 2
GPU 0000:04:00.0
    Product Name                    : GeForce GTX 690
    Product Brand                   : GeForce
    Display Mode                    : N/A
    Display Active                  : N/A
    Persistence Mode                : Disabled
    Accounting Mode                 : N/A
    Accounting Mode Buffer Size     : N/A
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-5b82af18-9ba4-72d1-32c1-ba3a68480c35
    Minor Number                    : 0
    VBIOS Version                   : 80.04.4C.00.0E
    MultiGPU Board                  : N/A
    Board ID                        : N/A
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : N/A
        OEM Object                  : N/A
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : N/A
    PCI
        Bus                         : 0x04
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x118810DE
        Bus Id                      : 0000:04:00.0
        Sub System Id               : 0x095B10DE
        GPU Link Info
            PCIe Generation
                Max                 : N/A
                Current             : N/A
            Link Width
                Max                 : N/A
                Current             : N/A
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : N/A
        Rx Throughput               : N/A
    Fan Speed                       : 30 %
    Performance State               : P8
    Clocks Throttle Reasons         : N/A
    FB Memory Usage
        Total                       : 1995 MiB
        Used                        : 510 MiB
        Free                        : 1485 MiB
    BAR1 Memory Usage
        Total                       : N/A
        Used                        : N/A
        Free                        : N/A
    Compute Mode                    : Default
    Utilization
        Gpu                         : N/A
        Memory                      : N/A
        Encoder                     : N/A
        Decoder                     : N/A
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 41 C
        GPU Shutdown Temp           : N/A
        GPU Slowdown Temp           : N/A
    Power Readings
        Power Management            : N/A
        Power Draw                  : N/A
        Power Limit                 : N/A
        Default Power Limit         : N/A
        Enforced Power Limit        : N/A
        Min Power Limit             : N/A
        Max Power Limit             : N/A
    Clocks
        Graphics                    : N/A
        SM                          : N/A
        Memory                      : N/A
        Video                       : N/A
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : N/A
        SM                          : N/A
        Memory                      : N/A
        Video                       : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes                       : N/A

GPU 0000:05:00.0
    Product Name                    : GeForce GTX 690
    Product Brand                   : GeForce
    Display Mode                    : N/A
    Display Active                  : N/A
    Persistence Mode                : Disabled
    Accounting Mode                 : N/A
    Accounting Mode Buffer Size     : N/A
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-b6f1bd21-300d-d2d1-eb23-fa8759875e8d
    Minor Number                    : 1
    VBIOS Version                   : 80.04.4C.00.0F
    MultiGPU Board                  : N/A
    Board ID                        : N/A
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : N/A
        OEM Object                  : N/A
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : N/A
    PCI
        Bus                         : 0x05
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x118810DE
        Bus Id                      : 0000:05:00.0
        Sub System Id               : 0x095B10DE
        GPU Link Info
            PCIe Generation
                Max                 : N/A
                Current             : N/A
            Link Width
                Max                 : N/A
                Current             : N/A
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays since reset         : 0
        Tx Throughput               : N/A
        Rx Throughput               : N/A
    Fan Speed                       : 30 %
    Performance State               : P8
    Clocks Throttle Reasons         : N/A
    FB Memory Usage
        Total                       : 1998 MiB
        Used                        : 516 MiB
        Free                        : 1482 MiB
    BAR1 Memory Usage
        Total                       : N/A
        Used                        : N/A
        Free                        : N/A
    Compute Mode                    : Default
    Utilization
        Gpu                         : N/A
        Memory                      : N/A
        Encoder                     : N/A
        Decoder                     : N/A
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending                     : N/A
    Temperature
        GPU Current Temp            : 40 C
        GPU Shutdown Temp           : N/A
        GPU Slowdown Temp           : N/A
    Power Readings
        Power Management            : N/A
        Power Draw                  : N/A
        Power Limit                 : N/A
        Default Power Limit         : N/A
        Enforced Power Limit        : N/A
        Min Power Limit             : N/A
        Max Power Limit             : N/A
    Clocks
        Graphics                    : N/A
        SM                          : N/A
        Memory                      : N/A
        Video                       : N/A
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : N/A
        SM                          : N/A
        Memory                      : N/A
        Video                       : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes                       : N/A

```

**Comment by flx42** [comment] 2016-11-15 02:05
Sorry, it looks like something is going awry with this particular GPU model. I will try to find one to see if I can reproduce the bug.
If any of you is willing to help, please try the following: `ltrace -f nvidia-docker-plugin`.
We need to narrow down which call causes the issue, then we can try the same sequence of calls in a simple C file, to see if it's a problem from nvidia-docker or from the NVML library.

Thank you!

**Comment by JonGerrand** [comment] 2016-11-15 06:22
I've attached the output. 
[ltrace.txt](https://github.com/NVIDIA/nvidia-docker/files/591205/ltrace.txt)

**Comment by flx42** [comment] 2016-11-15 18:20
Thanks @JonGerrand, can you also try `nvidia-smi topo -m`?

**Comment by flx42** [comment] 2016-11-15 18:43
Also, if someone can try the following code on his 690, that would be great:
```
#include <stdexcept>
#include <nvml.h>

#define NVML_CALL(call) \
    do { \
        nvmlReturn_t ret = call; \
        if (ret != NVML_SUCCESS) throw std::runtime_error(std::string(#call) + " error: " + std::to_string(ret)); \
    } while (0)

int main()
{
    NVML_CALL(nvmlInit());
    nvmlDevice_t dev1, dev2;
    NVML_CALL(nvmlDeviceGetHandleByIndex(0, &dev1));
    NVML_CALL(nvmlDeviceGetHandleByIndex(1, &dev2));
    nvmlGpuTopologyLevel_t topo;
    NVML_CALL(nvmlDeviceGetTopologyCommonAncestor(dev1, dev2, &topo));
}
```
You might need to tweak the index passed to `nvmlDeviceGetHandleByIndex`, in order to match the index `nvidia-smi` shows you for your 690 cards.

**Comment by flx42** [comment] 2016-11-18 00:32
Anyone willing to test this small code snippet?

**Comment by bbycroft** [comment] 2017-03-13 23:16
I have the same problem on a machine with several GeForce GTX 780 Ti's running NVIDIA 352.30 on Centos 7.

@flx42 I ran your code (slightly modified to get some more info) and got the output shown here:

[nvml_crash_output.txt](https://github.com/NVIDIA/nvidia-docker/files/839854/nvml_crash_output.txt)

The output shows that nvmlDeviceGetTopologyCommonAncestor returns the NVLM_UNKNOWN_ERROR code for certain pairs of GPUs. In this case, it's the ones that nvidia-smi reports "PIX = Path traverses a PCIe internal switch". Note that on another machine that also contains PIX (& SOC), nvmlDeviceGetTopologyCommonAncestor has no issues.

So it seems to be an issue in the NVIDIA driver rather than nvidia-docker-plugin.

Perhaps P2PLink could return P2PLinkUnknown if nvmlDeviceGetTopologyCommonAncestor returns NVLM_UNKNOWN_ERROR?

**Comment by flx42** [comment] 2017-03-13 23:44
@bbycroft Thanks! Could you try with a newer driver before I file this bug internally?
For instance, driver 375.XX. It's now the default shipped with CUDA 8.0

**Comment by bbycroft** [comment] 2017-03-14 22:59
@flx42 I've had a chance to test the code out with the newer driver versions, and also using a more recent kernel version: `3.10.0-514.10.2.el7.x86_64`. I tested with both the long-lived branch version 375.39, and the short-lived branch version 378.13. In both cases, I installed them from http://www.nvidia.com/object/unix.html. Output and other info shown here:

[nvml_crash_output_375.39.txt](https://github.com/NVIDIA/nvidia-docker/files/842966/nvml_crash_output_375.39.txt)
[nvml_crash_output_378.13.txt](https://github.com/NVIDIA/nvidia-docker/files/842967/nvml_crash_output_378.13.txt)

The result being that nvmlDeviceGetTopologyCommonAncestor crashes in the same way on this particular machine with the latest NVIDIA driver versions.

**Comment by flx42** [comment] 2017-03-15 00:02
@bbycroft thanks! A bug has been filed internally against NVML.

**Comment by rajserc** [comment] 2017-05-04 16:33
I had similar issue, in https://github.com/NVIDIA/nvidia-docker/blob/master/src/nvidia/devices.go
just overrided the device count to restrict to only gpu i wanted. And this seems to fix issue for me.
 `45         n, err := nvml.GetDeviceCount()
     46         if err != nil {
     47                 return nil, err
     48         }
     49         n = 1 //Instead of looking up problematic device, restrict the lookup to only to GPU that works
`

**Comment by flx42** [comment] 2017-05-20 20:02
@rajserc You seem to have a bigger problem than the original poster, your devices are in a bogus state and thus your system is probably unstable at this point.

**Comment by cliffwoolley** [comment] 2017-06-20 19:01
@bbycroft - Assuming you can still reproduce this issue, would you mind posting the nvml.log resulting from the following?

sudo -u nvidia-docker env __NVML_DBG_LVL=DEBUG __NVML_DBG_FILE=/tmp/nvml.log /usr/bin/nvidia-docker-plugin -s /var/lib/nvidia-docker

This will allow our NVML team to diagnose the source of the "unknown error".

**Comment by bbycroft** [comment] 2017-06-20 23:01
@cliffwoolley yes we can still reproduce the issue on our machine. I ran the command you supplied and got the following log output: [nvml.log.zip](https://github.com/NVIDIA/nvidia-docker/files/1089883/nvml.log.zip) (it appears to be a binary log, and I had to zip it for github upload)

Note that we're running a patched version of nvidia-docker-plugin that maps NVML_UNKNOWN_ERROR to P2PLinkUnknown, so the program doesn't crash on the first error. (I can still reproduce nvml_crash_output.txt from my previous comment)

**Comment by 2075** [comment] 2017-07-11 15:18
https://gist.github.com/2075/2d7e9aaed8d8fec927e4192c7c3361d1

any news on this?

**Comment by flx42** [comment] 2017-07-11 16:57
@2075 As far as I know, it has not been fixed in our latest drivers. Sorry, I don't know when it will be.

**Comment by 2075** [comment] 2017-07-11 17:41
@flx42 quite sad, we have a few workstations with gtx 690 sli setups, which we cannot dump. would be great to see a fix for that! is there a known workaround?

**Comment by flx42** [comment] 2017-07-11 17:44
You would have to modify the code, as mentioned by @bbycroft [above](https://github.com/NVIDIA/nvidia-docker/issues/206#issuecomment-309915690)

**Comment by 2075** [comment] 2017-07-11 18:26
@flx42 yes, that wouldn't be a big issue, I understood, there is more to do, than that?

**Comment by flx42** [comment] 2017-07-11 18:28
@2075 no that should be all I believe, you will need to generate your own package with `make deb` or `make rpm`.

**Comment by 2075** [comment] 2017-07-11 18:38
@flx42 ok, thx, will give it a shot.

**Comment by Setzar** [comment] 2017-07-12 14:15
@2075 @flx42  I also have a GTX690 that give me the same error. Did you find an issue to this ? Thank you

**Comment by 3XX0** [comment] 2017-11-14 06:27
Closing, this bug is specific to 1.0. Feel free to open another issue if you can reproduce with 2.0/master.

**Closed by 3XX0** 2017-11-14 06:27 UTC
Labels: bug
