### ISSUE TITLE
nvidia-container-toolkit 1.6.0~rc.1-1 breaks everything.

### ISSUE THREAD

**Issue by DimanNe** [NVIDIA/nvidia-docker#1534] opened 2021-08-14 20:10 UTC
### 1. Issue or feature description
It looks like after a recent update in Kubuntu (where amongst other packages, `nvidia-container-toolkit` was updated), I cannot start docker with `--runtime nvidia` anymore:

```
docker run -it --rm --runtime nvidia nvidia/cuda:11.4.1-devel-ubuntu18.04 /bin/bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #1:: error running hook: signal: segmentation fault (core dumped), stdout: , stderr:: unknown.
```

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`

```
nvidia-container-cli -k -d /dev/tty info
-- WARNING, the following logs are for debugging purposes only --

I0814 20:01:11.365318 23361 nvc.c:372] initializing library context (version=1.5.0~rc.1, build=5884d4232da9109423f55e79d57df264991c27cf)
I0814 20:01:11.365338 23361 nvc.c:346] using root /
I0814 20:01:11.365340 23361 nvc.c:347] using ldcache /etc/ld.so.cache
I0814 20:01:11.365341 23361 nvc.c:348] using unprivileged user 1000:1000
fish: “nvidia-container-cli -k -d /dev…” terminated by signal SIGSEGV (Address boundary error)
```

 - [ ] Kernel version from `uname -a`

```
Linux Impedance 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`

```
nvidia-smi -a

==============NVSMI LOG==============

Timestamp                                 : Sat Aug 14 21:02:09 2021
Driver Version                            : 470.57.02
CUDA Version                              : 11.4

Attached GPUs                             : 2
```

 - [ ] Docker version from `docker version`

```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:17:52 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                          Version                    Architecture Description
+++-=============================-==========================-============-=========================================================
un  libgldispatch0-nvidia         <none>                     <none>       (no description available)
ii  libnvidia-cfg1-470:amd64      470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA binary OpenGL/GLX configuration library
un  libnvidia-cfg1-any            <none>                     <none>       (no description available)
un  libnvidia-common              <none>                     <none>       (no description available)
ii  libnvidia-common-470          470.57.02-0ubuntu0.21.04.1 all          Shared files used by the NVIDIA libraries
un  libnvidia-compute             <none>                     <none>       (no description available)
rc  libnvidia-compute-460:amd64   460.91.03-0ubuntu0.21.04.1 amd64        NVIDIA libcompute package
ii  libnvidia-compute-470:amd64   470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA libcompute package
ii  libnvidia-compute-470:i386    470.57.02-0ubuntu0.21.04.1 i386         NVIDIA libcompute package
ii  libnvidia-container-tools     1.5.0~rc.1-1               amd64        NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64    1.5.0~rc.1-1               amd64        NVIDIA container runtime library
un  libnvidia-decode              <none>                     <none>       (no description available)
ii  libnvidia-decode-470:amd64    470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA Video Decoding runtime libraries
ii  libnvidia-decode-470:i386     470.57.02-0ubuntu0.21.04.1 i386         NVIDIA Video Decoding runtime libraries
un  libnvidia-encode              <none>                     <none>       (no description available)
ii  libnvidia-encode-470:amd64    470.57.02-0ubuntu0.21.04.1 amd64        NVENC Video Encoding runtime library
ii  libnvidia-encode-470:i386     470.57.02-0ubuntu0.21.04.1 i386         NVENC Video Encoding runtime library
un  libnvidia-extra               <none>                     <none>       (no description available)
ii  libnvidia-extra-470:amd64     470.57.02-0ubuntu0.21.04.1 amd64        Extra libraries for the NVIDIA driver
un  libnvidia-fbc1                <none>                     <none>       (no description available)
ii  libnvidia-fbc1-470:amd64      470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA OpenGL-based Framebuffer Capture runtime library
ii  libnvidia-fbc1-470:i386       470.57.02-0ubuntu0.21.04.1 i386         NVIDIA OpenGL-based Framebuffer Capture runtime library
un  libnvidia-gl                  <none>                     <none>       (no description available)
un  libnvidia-gl-390              <none>                     <none>       (no description available)
un  libnvidia-gl-450              <none>                     <none>       (no description available)
un  libnvidia-gl-460              <none>                     <none>       (no description available)
ii  libnvidia-gl-470:amd64        470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
ii  libnvidia-gl-470:i386         470.57.02-0ubuntu0.21.04.1 i386         NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
un  libnvidia-ifr1                <none>                     <none>       (no description available)
ii  libnvidia-ifr1-470:amd64      470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA OpenGL-based Inband Frame Readback runtime library
ii  libnvidia-ifr1-470:i386       470.57.02-0ubuntu0.21.04.1 i386         NVIDIA OpenGL-based Inband Frame Readback runtime library
un  libnvidia-ml1                 <none>                     <none>       (no description available)
un  nvidia-384                    <none>                     <none>       (no description available)
un  nvidia-390                    <none>                     <none>       (no description available)
un  nvidia-common                 <none>                     <none>       (no description available)
un  nvidia-compute-utils          <none>                     <none>       (no description available)
rc  nvidia-compute-utils-460      460.91.03-0ubuntu0.21.04.1 amd64        NVIDIA compute utilities
ii  nvidia-compute-utils-470      470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA compute utilities
ii  nvidia-container-runtime      3.5.0-1                    amd64        NVIDIA container runtime
un  nvidia-container-runtime-hook <none>                     <none>       (no description available)
ii  nvidia-container-toolkit      1.6.0~rc.1-1               amd64        NVIDIA container runtime hook
rc  nvidia-dkms-460               460.91.03-0ubuntu0.21.04.1 amd64        NVIDIA DKMS package
ii  nvidia-dkms-470               470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA DKMS package
...skipping...
ii  libnvidia-encode-470:i386     470.57.02-0ubuntu0.21.04.1 i386         NVENC Video Encoding runtime library
un  libnvidia-extra               <none>                     <none>       (no description available)
ii  libnvidia-extra-470:amd64     470.57.02-0ubuntu0.21.04.1 amd64        Extra libraries for the NVIDIA driver
un  libnvidia-fbc1                <none>                     <none>       (no description available)
ii  libnvidia-fbc1-470:amd64      470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA OpenGL-based Framebuffer Capture runtime library
ii  libnvidia-fbc1-470:i386       470.57.02-0ubuntu0.21.04.1 i386         NVIDIA OpenGL-based Framebuffer Capture runtime library
un  libnvidia-gl                  <none>                     <none>       (no description available)
un  libnvidia-gl-390              <none>                     <none>       (no description available)
un  libnvidia-gl-450              <none>                     <none>       (no description available)
un  libnvidia-gl-460              <none>                     <none>       (no description available)
ii  libnvidia-gl-470:amd64        470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
ii  libnvidia-gl-470:i386         470.57.02-0ubuntu0.21.04.1 i386         NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
un  libnvidia-ifr1                <none>                     <none>       (no description available)
ii  libnvidia-ifr1-470:amd64      470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA OpenGL-based Inband Frame Readback runtime library
ii  libnvidia-ifr1-470:i386       470.57.02-0ubuntu0.21.04.1 i386         NVIDIA OpenGL-based Inband Frame Readback runtime library
un  libnvidia-ml1                 <none>                     <none>       (no description available)
un  nvidia-384                    <none>                     <none>       (no description available)
un  nvidia-390                    <none>                     <none>       (no description available)
un  nvidia-common                 <none>                     <none>       (no description available)
un  nvidia-compute-utils          <none>                     <none>       (no description available)
rc  nvidia-compute-utils-460      460.91.03-0ubuntu0.21.04.1 amd64        NVIDIA compute utilities
ii  nvidia-compute-utils-470      470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA compute utilities
ii  nvidia-container-runtime      3.5.0-1                    amd64        NVIDIA container runtime
un  nvidia-container-runtime-hook <none>                     <none>       (no description available)
ii  nvidia-container-toolkit      1.6.0~rc.1-1               amd64        NVIDIA container runtime hook
rc  nvidia-dkms-460               460.91.03-0ubuntu0.21.04.1 amd64        NVIDIA DKMS package
ii  nvidia-dkms-470               470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA DKMS package
un  nvidia-dkms-kernel            <none>                     <none>       (no description available)
un  nvidia-docker                 <none>                     <none>       (no description available)
ii  nvidia-docker2                2.6.0-1                    all          nvidia-docker CLI wrapper
ii  nvidia-driver-470             470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA driver metapackage
un  nvidia-driver-binary          <none>                     <none>       (no description available)
un  nvidia-kernel-common          <none>                     <none>       (no description available)
rc  nvidia-kernel-common-460      460.91.03-0ubuntu0.21.04.1 amd64        Shared files used with the kernel module
ii  nvidia-kernel-common-470      470.57.02-0ubuntu0.21.04.1 amd64        Shared files used with the kernel module
un  nvidia-kernel-source          <none>                     <none>       (no description available)
un  nvidia-kernel-source-460      <none>                     <none>       (no description available)
ii  nvidia-kernel-source-470      470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA kernel source package
un  nvidia-libopencl1-dev         <none>                     <none>       (no description available)
un  nvidia-opencl-icd             <none>                     <none>       (no description available)
un  nvidia-persistenced           <none>                     <none>       (no description available)
ii  nvidia-prime                  0.8.16.1                   all          Tools to enable NVIDIA's Prime
ii  nvidia-settings               470.57.01-0ubuntu0.21.04.1 amd64        Tool for configuring the NVIDIA graphics driver
un  nvidia-settings-binary        <none>                     <none>       (no description available)
un  nvidia-smi                    <none>                     <none>       (no description available)
un  nvidia-utils                  <none>                     <none>       (no description available)
ii  nvidia-utils-470              470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA driver support binaries
ii  xserver-xorg-video-nvidia-470 470.57.02-0ubuntu0.21.04.1 amd64        NVIDIA binary Xorg driver
```

 - [ ] NVIDIA container library version from `nvidia-container-cli -V`

```
version: 1.5.0~rc.1
build date: 2021-08-13T09:32+00:00
build revision: 5884d4232da9109423f55e79d57df264991c27cf
build compiler: x86_64-linux-gnu-gcc-7 7.5.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections
```

 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))

/var/log/nvidia-container-toolkit.log
```
I0814 20:05:40.119586 25515 nvc.c:372] initializing library context (version=1.5.0~rc.1, build=5884d4232da9109423f55e79d57df264991c27cf)
I0814 20:05:40.119614 25515 nvc.c:346] using root /
I0814 20:05:40.119617 25515 nvc.c:347] using ldcache /etc/ld.so.cache
I0814 20:05:40.119620 25515 nvc.c:348] using unprivileged user 65534:65534
```

/var/log/nvidia-container-runtime.log
```
2021/08/14 21:05:07 Using bundle directory: /run/containerd/io.containerd.runtime.v2.task/moby/f53dd49a2079c65f391a53ccb14937fe3dff50286241701cec0438480551e47d
2021/08/14 21:05:07 Using OCI specification file path: /run/containerd/io.containerd.runtime.v2.task/moby/f53dd49a2079c65f391a53ccb14937fe3dff50286241701cec0438480551e47d/config.json
2021/08/14 21:05:07 Looking for runtime binary 'docker-runc'
2021/08/14 21:05:07 Runtime binary 'docker-runc' not found: exec: "docker-runc": executable file not found in $PATH
2021/08/14 21:05:07 Looking for runtime binary 'runc'
2021/08/14 21:05:07 Found runtime binary '/usr/bin/runc'
2021/08/14 21:05:07 Running nvidia-container-runtime

2021/08/14 21:05:07 'create' command detected; modification required
2021/08/14 21:05:07 prestart hook path: /usr/bin/nvidia-container-runtime-hook
```

**Comment by DimanNe** [comment] 2021-08-14 20:11
# Update: Downgrading nvidia-container-toolkit to 1.5.1-1 - HELPED

```
docker run -it --rm --runtime nvidia ubuntu:21.04 /bin/bash
root@a38cd4b96ffc:/# 

```

**Comment by DimanNe** [comment] 2021-08-14 20:24
# Update: downgrading HELPED!

```
apt install libnvidia-container1=1.4.0-1 libnvidia-container-tools=1.4.0-1 nvidia-container-toolkit=1.5.1-1
```

**Comment by chrisman1015** [comment] 2021-08-15 00:28
I had the same problem. I tried a fresh install today and kept getting an error. Couldn't figure out what was wrong but the downgrade made it work for me immediately.

**Comment by elezar** [comment] 2021-08-16 10:30
Hi. Yes, there is an issue in the rc.1 packages that were released on Friday to the experimental repos. We have removed these packages from the repos while we work on the fix. Using the versions from the stable repos should address the issues.

**Comment by elezar** [comment] 2021-08-17 07:56
This is a duplicate of #1533. There is a bug in libnvidia-container-tools-1.5.0~rc.1. Closing this issue. Please reopen if required.

**Closed by elezar** 2021-08-17 07:56 UTC

**Comment by mikedh** [comment] 2021-08-18 16:25
Hey, I think this is still happening. On an Ubuntu 20.04 machine (GCP Tesla T4 instance) running `apt-get update` / `apt-get upgrade` will install `1.6.0~rc.1-1` which segfaults immediately:
```
Setting up nvidia-container-toolkit (1.6.0~rc.1-1) ...
```
My containers fail without log messages, and `nvidia-container-cli` segaults also without debugable messages:
```
nvidia-container-cli -k -d /def/tty info
Segmentation fault (core dumped)
```

@DimanNe suggestion to downgrade fixes the issue.

**Comment by elezar** [comment] 2021-08-18 17:09
@mikedh I pulled the `nvidia-container-toolkit_1.6.0~rc.1-1` and `libnvidia-container-tools_1.5.0~rc.1-1` packages that contained the bug. Please ensure that these are not available in your cache.

Alternatively, remove the experimental repositories from any repos list that you may have since this is where the packages were published.

**Comment by mikedh** [comment] 2021-08-18 17:45
No worries and sorry for the vague reporting. I just did another `apt-get update`/ `apt-get upgrade` and this issue does appear to be fully fixed now, thanks! 

On closer inspection this instance was actually running Ubuntu *18.04* and pulling from https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/amd64 which looks like I got from [the official installation guide for docker+nvidia](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker)

**Comment by elezar** [comment] 2021-08-19 07:16
@mikedh thanks for checking again and happy that the problematic packages are no longer being pulled.

For clarity, the 18.04 packages are used for most Ubuntu flavours and we point to the 18.04 repositories directly in the various lists instead of redirecting later. Also, the experimental repo is the suggested way to get access to newer features. We are working on improving our release process to ensure that we don't inadvertently break packages there again.
