### ISSUE TITLE
Cannot get Image based on Ubuntu20.04 to detect GPU

### ISSUE THREAD

**Issue by Mithrandir2k18** [NVIDIA/nvidia-docker#1415] opened 2020-11-12 02:34 UTC
### 1. Issue or feature description
I am trying to build a docker-image based on Ubuntu 20.04 with tensorflow-gpu, but when I try to test if the GPU is available in tensorflow, it gives me an error.

### 2. Steps to reproduce the issue
Build the following image:
```
FROM ubuntu:20.04
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata keyboard-configuration
RUN apt-get update && apt-get install -y wget git curl nvidia-cuda-toolkit gcc g++ make cmake
# install conda, this makes getting cudnn easier
RUN curl https://repo.anaconda.com/archive/Anaconda3-2020.07-Linux-x86_64.sh -o condainstall.sh && bash condainstall.sh -b && rm condainstall.sh
ENV PATH /root/anaconda3/bin:$PATH
RUN conda update conda && conda update anaconda && conda update --all && yes | conda init bash
RUN yes | conda create -n myenv tensorflow-gpu python=3.8 --force && conda clean --all --yes
# use the new environment:
SHELL ["conda", "run", "-n", "myenv", "/bin/bash", "-c"]
```
Then start the image, `conda activate myenv`, `python`, `import tensorflow as tf;tf.test.is_gpu_available()`. This results in the following output:

```
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.test.is_gpu_available()
WARNING:tensorflow:From <stdin>:1: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2020-11-12 02:20:49.046071: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-11-12 02:20:49.055532: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3801850000 Hz
2020-11-12 02:20:49.056500: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55e3b9c48490 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-12 02:20:49.056534: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-11-12 02:20:49.057467: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-11-12 02:20:49.058027: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-11-12 02:20:49.058059: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: bcbd4791f5ee
2020-11-12 02:20:49.058074: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: bcbd4791f5ee
2020-11-12 02:20:49.058166: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 440.95.1
2020-11-12 02:20:49.058202: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 455.38.0
2020-11-12 02:20:49.058217: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 455.38.0 does not match DSO version 440.95.1 -- cannot find working devices in this configuration
False
```

Testing nvidia-docker with other images, e.g. `tensorflow/tensorflow:latest-gpu` works as expected, so my host seems to be setup correctly.

**Comment by klueska** [comment] 2020-11-12 09:43
This seems like a duplicate of https://github.com/NVIDIA/nvidia-docker/issues/1414

**Closed by klueska** 2020-11-12 09:43 UTC
