### ISSUE TITLE
Cannot use sudo command inside Nvidia-Docker image

### ISSUE THREAD

**Issue by schroeder-dewitt** [NVIDIA/nvidia-docker#673] opened 2018-03-18 14:59 UTC
Dear All,

I build the following Dockerfile

````
FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

RUN apt-get update && \
      apt-get -y install sudo

RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo

USER docker

CMD /bin/bash
````

using 

> nvidia-docker build -t sudoprob

and when I run it using

> nvidia-docker run -it sudoprob

and, as user docker inside the container, I call 

> sudo apt-get update

then I get the following error:

> sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

I did a little bit of research into the issue and had a look at /proc/mount etc, but I am not able to determine whether the root partition / is mounted with nosuid option or not. In any case, I think this is probably something that needs to be fixed by the image developers. 

I need to be able to use sudo because I am running a lot of 3rdparty software install scripts that don't accept to be run as root and any workarounds I can think of require hours of chmodding and chowning of installation files. I don't want to / cannot hack those installation scripts to be ok with using root.

Is there a workaround, or will this be fixed at some point?

Thanks a lot and regards

Christian Schroeder de Witt

PS: I am using 

> Docker version 17.12.1-ce, build 7390fc6

**Comment by flx42** [comment] 2018-03-18 19:07
Which version of `libnvidia-container` do you have?

**Comment by schroeder-dewitt** [comment] 2018-03-18 22:30
> 1.0.0~beta.1-1

Should I upgrade manually?

**Comment by flx42** [comment] 2018-03-19 02:07
This issue should have been fixed by https://github.com/NVIDIA/libnvidia-container/commit/584bca59ecd7e67011b83d90cc5ac07db35dd47c, so that's weird.
Can you do `findmnt` inside the container?

**Comment by schroeder-dewitt** [comment] 2018-03-20 01:41
`TARGET                           SOURCE               FSTYPE  OPTIONS
/                                overlay              overlay rw,relatime,lowerd
|-/proc                          proc                 proc    rw,nosuid,nodev,no
| |-/proc/asound                 proc[/asound]        proc    ro,relatime
| |-/proc/bus                    proc[/bus]           proc    ro,relatime
| |-/proc/fs                     proc[/fs]            proc    ro,relatime
| |-/proc/irq                    proc[/irq]           proc    ro,relatime
| |-/proc/sys                    proc[/sys]           proc    ro,relatime
| |-/proc/sysrq-trigger          proc[/sysrq-trigger] proc    ro,relatime
| |-/proc/kcore                  tmpfs[/null]         tmpfs   rw,nosuid,size=655
| |-/proc/timer_list             tmpfs[/null]         tmpfs   rw,nosuid,size=655
| |-/proc/sched_debug            tmpfs[/null]         tmpfs   rw,nosuid,size=655
| `-/proc/scsi                   tmpfs                tmpfs   ro,relatime
|-/dev                           tmpfs                tmpfs   rw,nosuid,size=655
| |-/dev/console                 devpts[/0]           devpts  rw,nosuid,noexec,r
| |-/dev/pts                     devpts               devpts  rw,nosuid,noexec,r
| |-/dev/mqueue                  mqueue               mqueue  rw,nosuid,nodev,no
| `-/dev/shm                     shm                  tmpfs   rw,nosuid,nodev,no
|-/sys                           sysfs                sysfs   ro,nosuid,nodev,no
| |-/sys/firmware                tmpfs                tmpfs   ro,relatime
| `-/sys/fs/cgroup               tmpfs                tmpfs   ro,nosuid,nodev,no
|   |-/sys/fs/cgroup/systemd     cgroup[/docker/c3e516ede1e7501e66981ee97ffccc778ec1dc7e6bc82d6cbe1d76cb5da117f6]
|   |                                                 cgroup  ro,nosuid,nodev,no
|   |-/sys/fs/cgroup/hugetlb     cgroup[/docker/c3e516ede1e7501e66981ee97ffccc778ec1dc7e6bc82d6cbe1d76cb5da117f6]
|   |                                                 cgroup  ro,nosuid,nodev,no
|   |-/sys/fs/cgroup/net_cls,net_prio
|   |                            cgroup[/docker/c3e516ede1e7501e66981ee97ffccc778ec1dc7e6bc82d6cbe1d76cb5da117f6]
|   |                                                 cgroup  ro,nosuid,nodev,no
|   |-/sys/fs/cgroup/blkio       cgroup[/docker/c3e516ede1e7501e66981ee97ffccc778ec1dc7e6bc82d6cbe1d76cb5da117f6]
|   |                                                 cgroup  ro,nosuid,nodev,no
|   |-/sys/fs/cgroup/cpuset      cgroup[/docker/c3e516ede1e7501e66981ee97ffccc778ec1dc7e6bc82d6cbe1d76cb5da117f6]
|   |                                                 cgroup  ro,nosuid,nodev,no
|   |-/sys/fs/cgroup/pids        cgroup[/docker/c3e516ede1e7501e66981ee97ffccc778ec1dc7e6bc82d6cbe1d76cb5da117f6]
|   |                                                 cgroup  ro,nosuid,nodev,no
|   |-/sys/fs/cgroup/cpu,cpuacct cgroup[/docker/c3e516ede1e7501e66981ee97ffccc778ec1dc7e6bc82d6cbe1d76cb5da117f6]
|   |                                                 cgroup  ro,nosuid,nodev,no
|   |-/sys/fs/cgroup/rdma        cgroup               cgroup  ro,nosuid,nodev,no
|   |-/sys/fs/cgroup/perf_event  cgroup[/docker/c3e516ede1e7501e66981ee97ffccc778ec1dc7e6bc82d6cbe1d76cb5da117f6]
|   |                                                 cgroup  ro,nosuid,nodev,no
|   |-/sys/fs/cgroup/devices     cgroup[/docker/c3e516ede1e7501e66981ee97ffccc778ec1dc7e6bc82d6cbe1d76cb5da117f6]
|   |                                                 cgroup  ro,nosuid,nodev,no
|   |-/sys/fs/cgroup/freezer     cgroup[/docker/c3e516ede1e7501e66981ee97ffccc778ec1dc7e6bc82d6cbe1d76cb5da117f6]
|   |                                                 cgroup  ro,nosuid,nodev,no
|   `-/sys/fs/cgroup/memory      cgroup[/docker/c3e516ede1e7501e66981ee97ffccc778ec1dc7e6bc82d6cbe1d76cb5da117f6]
|                                                     cgroup  ro,nosuid,nodev,no
|-/etc/resolv.conf               /dev/sda2[/cs/tools/docker/containers/c3e516ede1e7501e66981ee97ffccc778ec1dc7e6bc82d6cbe1d76cb5da117f6/resolv.conf]
|                                                     ext4    rw,nosuid,nodev,re
|-/etc/hostname                  /dev/sda2[/cs/tools/docker/containers/c3e516ede1e7501e66981ee97ffccc778ec1dc7e6bc82d6cbe1d76cb5da117f6/hostname]
|                                                     ext4    rw,nosuid,nodev,re
`-/etc/hosts                     /dev/sda2[/cs/tools/docker/containers/c3e516ede1e7501e66981ee97ffccc778ec1dc7e6bc82d6cbe1d76cb5da117f6/hosts]
                                                      ext4    rw,nosuid,nodev,re
`

**Comment by schroeder-dewitt** [comment] 2018-03-20 01:47
In short, it does not seem as if root ( / ) was mounted with nosuid. So I don't know what's going on at all!

/usr/bin/sudo has the following permissions:
-rwsr-xr-x 1 root root 136808 Jul  4  2017 sudo

So that should be fine as well, I presume?

**Comment by flx42** [comment] 2018-03-20 01:51
You didn't run this container with `--runtime=nvidia`, right?

**Comment by schroeder-dewitt** [comment] 2018-03-20 01:54
> nvidia-docker run --runtime=nvidia -u root -it sudoprob

nor

> docker run --runtime=nvidia -u root -it sudoprob

works...

**Comment by schroeder-dewitt** [comment] 2018-03-20 01:54
(I mean i can use sudo as root, but when i do "su docker" i cannot anymore)

**Comment by flx42** [comment] 2018-03-20 01:56
I think there is a misunderstanding, what's the output of `docker run --rm --runtime=nvidia nvidia/cuda:9.0-base findmnt`?

**Comment by schroeder-dewitt** [comment] 2018-03-20 02:07
TARGET                                                          SOURCE                                                                                                              FSTYPE   OPTIONS
/                                                               overlay                                                                                                             overlay  rw,relatime,lowerdir=/media/data/cs/tools/docker/overlay2/l/DX6XXIM55MQS3FQFF6Q4R6ER6W:/media/data/cs/tools/docker/overlay2/l/T6VN7455SXR4QNNMDJPVSO3WKH:/media/data/cs/tools/docker/overlay2/l/6X2AAWOY7IAUD3FDZUO5BMPMNZ:/media/data/cs/tools/docker/overlay2/l/CMGW6HGASOZVXO3323OXGOBOPR:/media/data/cs/tools/docker/overlay2/l/NNQJXZQ334JXBUGQ6DZPFOSNJN:/media/data/cs/tools/docker/overlay2/l/L6NYA4DKDX2547TDHOJB37LZDR:/media/data/cs/tools/docker/overlay2/l/BNWQ3Q2G3CT7PEFG6TSXXHZGL5:/media/data/cs/tools/docker/overlay2/l/BU2LFR6SJUXX6HY3GF6W37FUZF:/media/data/cs/tools/docker/overlay2/l/J5F673MCKIJSNBLC4ILNEOOWQ2,upperdir=/media/data/cs/tools/docker/overlay2/ec8aa104b4ff8a2a5421e06523555446b35c60d4f5910ef6315ca94e7aa26b3b/diff,workdir=/media/data/cs/tools/docker/overlay2/ec8aa104b4ff8a2a5421e06523555446b35c60d4f5910ef6315ca94e7aa26b3b/work
|-/proc                                                         proc                                                                                                                proc     rw,nosuid,nodev,noexec,relatime
| |-/proc/asound                                                proc[/asound]                                                                                                       proc     ro,relatime
| |-/proc/bus                                                   proc[/bus]                                                                                                          proc     ro,relatime
| |-/proc/fs                                                    proc[/fs]                                                                                                           proc     ro,relatime
| |-/proc/irq                                                   proc[/irq]                                                                                                          proc     ro,relatime
| |-/proc/sys                                                   proc[/sys]                                                                                                          proc     ro,relatime
| |-/proc/sysrq-trigger                                         proc[/sysrq-trigger]                                                                                                proc     ro,relatime
| |-/proc/kcore                                                 tmpfs[/null]                                                                                                        tmpfs    rw,nosuid,size=65536k,mode=755
| |-/proc/timer_list                                            tmpfs[/null]                                                                                                        tmpfs    rw,nosuid,size=65536k,mode=755
| |-/proc/sched_debug                                           tmpfs[/null]                                                                                                        tmpfs    rw,nosuid,size=65536k,mode=755
| |-/proc/scsi                                                  tmpfs                                                                                                               tmpfs    ro,relatime
| `-/proc/driver/nvidia                                         tmpfs                                                                                                               tmpfs    rw,nosuid,nodev,noexec,relatime,mode=555
|   `-/proc/driver/nvidia/gpus/0000:01:00.0                     proc[/driver/nvidia/gpus/0000:01:00.0]                                                                              proc     ro,nosuid,nodev,noexec,relatime
|-/dev                                                          tmpfs                                                                                                               tmpfs    rw,nosuid,size=65536k,mode=755
| |-/dev/pts                                                    devpts                                                                                                              devpts   rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666
| |-/dev/mqueue                                                 mqueue                                                                                                              mqueue   rw,nosuid,nodev,noexec,relatime
| |-/dev/shm                                                    shm                                                                                                                 tmpfs    rw,nosuid,nodev,noexec,relatime,size=65536k
| |-/dev/nvidiactl                                              udev[/nvidiactl]                                                                                                    devtmpfs ro,nosuid,noexec,relatime,size=16372584k,nr_inodes=4093146,mode=755
| |-/dev/nvidia-uvm                                             udev[/nvidia-uvm]                                                                                                   devtmpfs ro,nosuid,noexec,relatime,size=16372584k,nr_inodes=4093146,mode=755
| |-/dev/nvidia-uvm-tools                                       udev[/nvidia-uvm-tools]                                                                                             devtmpfs ro,nosuid,noexec,relatime,size=16372584k,nr_inodes=4093146,mode=755
| `-/dev/nvidia0                                                udev[/nvidia0]                                                                                                      devtmpfs ro,nosuid,noexec,relatime,size=16372584k,nr_inodes=4093146,mode=755
|-/sys                                                          sysfs                                                                                                               sysfs    ro,nosuid,nodev,noexec,relatime
| |-/sys/firmware                                               tmpfs                                                                                                               tmpfs    ro,relatime
| `-/sys/fs/cgroup                                              tmpfs                                                                                                               tmpfs    ro,nosuid,nodev,noexec,relatime,mode=755
|   |-/sys/fs/cgroup/systemd                                    cgroup[/docker/8f99e750e2cf5ea4ad0183e60da36ed67121e2bacaeee948129453de87e3a96c]                                    cgroup   ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
|   |-/sys/fs/cgroup/hugetlb                                    cgroup[/docker/8f99e750e2cf5ea4ad0183e60da36ed67121e2bacaeee948129453de87e3a96c]                                    cgroup   ro,nosuid,nodev,noexec,relatime,hugetlb
|   |-/sys/fs/cgroup/net_cls,net_prio                           cgroup[/docker/8f99e750e2cf5ea4ad0183e60da36ed67121e2bacaeee948129453de87e3a96c]                                    cgroup   ro,nosuid,nodev,noexec,relatime,net_cls,net_prio
|   |-/sys/fs/cgroup/blkio                                      cgroup[/docker/8f99e750e2cf5ea4ad0183e60da36ed67121e2bacaeee948129453de87e3a96c]                                    cgroup   ro,nosuid,nodev,noexec,relatime,blkio
|   |-/sys/fs/cgroup/cpuset                                     cgroup[/docker/8f99e750e2cf5ea4ad0183e60da36ed67121e2bacaeee948129453de87e3a96c]                                    cgroup   ro,nosuid,nodev,noexec,relatime,cpuset
|   |-/sys/fs/cgroup/pids                                       cgroup[/docker/8f99e750e2cf5ea4ad0183e60da36ed67121e2bacaeee948129453de87e3a96c]                                    cgroup   ro,nosuid,nodev,noexec,relatime,pids
|   |-/sys/fs/cgroup/cpu,cpuacct                                cgroup[/docker/8f99e750e2cf5ea4ad0183e60da36ed67121e2bacaeee948129453de87e3a96c]                                    cgroup   ro,nosuid,nodev,noexec,relatime,cpu,cpuacct
|   |-/sys/fs/cgroup/rdma                                       cgroup                                                                                                              cgroup   ro,nosuid,nodev,noexec,relatime,rdma
|   |-/sys/fs/cgroup/perf_event                                 cgroup[/docker/8f99e750e2cf5ea4ad0183e60da36ed67121e2bacaeee948129453de87e3a96c]                                    cgroup   ro,nosuid,nodev,noexec,relatime,perf_event
|   |-/sys/fs/cgroup/devices                                    cgroup[/docker/8f99e750e2cf5ea4ad0183e60da36ed67121e2bacaeee948129453de87e3a96c]                                    cgroup   ro,nosuid,nodev,noexec,relatime,devices
|   |-/sys/fs/cgroup/freezer                                    cgroup[/docker/8f99e750e2cf5ea4ad0183e60da36ed67121e2bacaeee948129453de87e3a96c]                                    cgroup   ro,nosuid,nodev,noexec,relatime,freezer
|   `-/sys/fs/cgroup/memory                                     cgroup[/docker/8f99e750e2cf5ea4ad0183e60da36ed67121e2bacaeee948129453de87e3a96c]                                    cgroup   ro,nosuid,nodev,noexec,relatime,memory
|-/etc/resolv.conf                                              /dev/sda2[/cs/tools/docker/containers/8f99e750e2cf5ea4ad0183e60da36ed67121e2bacaeee948129453de87e3a96c/resolv.conf] ext4     rw,nosuid,nodev,relatime,data=ordered
|-/etc/hostname                                                 /dev/sda2[/cs/tools/docker/containers/8f99e750e2cf5ea4ad0183e60da36ed67121e2bacaeee948129453de87e3a96c/hostname]    ext4     rw,nosuid,nodev,relatime,data=ordered
|-/etc/hosts                                                    /dev/sda2[/cs/tools/docker/containers/8f99e750e2cf5ea4ad0183e60da36ed67121e2bacaeee948129453de87e3a96c/hosts]       ext4     rw,nosuid,nodev,relatime,data=ordered
|-/usr/bin/nvidia-smi                                           /dev/mapper/ubuntu-ubuntu--root[/usr/lib/nvidia-387/bin/nvidia-smi]                                                 ext4     ro,nosuid,nodev,relatime,errors=remount-ro,data=ordered
|-/usr/bin/nvidia-debugdump                                     /dev/mapper/ubuntu-ubuntu--root[/usr/lib/nvidia-387/bin/nvidia-debugdump]                                           ext4     ro,nosuid,nodev,relatime,errors=remount-ro,data=ordered
|-/usr/bin/nvidia-persistenced                                  /dev/mapper/ubuntu-ubuntu--root[/usr/lib/nvidia-387/bin/nvidia-persistenced]                                        ext4     ro,nosuid,nodev,relatime,errors=remount-ro,data=ordered
|-/usr/bin/nvidia-cuda-mps-control                              /dev/mapper/ubuntu-ubuntu--root[/usr/lib/nvidia-387/bin/nvidia-cuda-mps-control]                                    ext4     ro,nosuid,nodev,relatime,errors=remount-ro,data=ordered
|-/usr/bin/nvidia-cuda-mps-server                               /dev/mapper/ubuntu-ubuntu--root[/usr/lib/nvidia-387/bin/nvidia-cuda-mps-server]                                     ext4     ro,nosuid,nodev,relatime,errors=remount-ro,data=ordered
|-/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.387.34              /dev/mapper/ubuntu-ubuntu--root[/usr/lib/nvidia-387/libnvidia-ml.so.387.34]                                         ext4     ro,nosuid,nodev,relatime,errors=remount-ro,data=ordered
|-/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.387.34             /dev/mapper/ubuntu-ubuntu--root[/usr/lib/nvidia-387/libnvidia-cfg.so.387.34]                                        ext4     ro,nosuid,nodev,relatime,errors=remount-ro,data=ordered
|-/usr/lib/x86_64-linux-gnu/libcuda.so.387.34                   /dev/mapper/ubuntu-ubuntu--root[/usr/lib/x86_64-linux-gnu/libcuda.so.387.34]                                        ext4     ro,nosuid,nodev,relatime,errors=remount-ro,data=ordered
|-/usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.387.34          /dev/mapper/ubuntu-ubuntu--root[/usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.387.34]                               ext4     ro,nosuid,nodev,relatime,errors=remount-ro,data=ordered
|-/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.387.34  /dev/mapper/ubuntu-ubuntu--root[/usr/lib/nvidia-387/libnvidia-ptxjitcompiler.so.387.34]                             ext4     ro,nosuid,nodev,relatime,errors=remount-ro,data=ordered
|-/usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.387.34 /dev/mapper/ubuntu-ubuntu--root[/usr/lib/nvidia-387/libnvidia-fatbinaryloader.so.387.34]                            ext4     ro,nosuid,nodev,relatime,errors=remount-ro,data=ordered
|-/usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.387.34        /dev/mapper/ubuntu-ubuntu--root[/usr/lib/nvidia-387/libnvidia-compiler.so.387.34]                                   ext4     ro,nosuid,nodev,relatime,errors=remount-ro,data=ordered
`-/run/nvidia-persistenced/socket                               tmpfs[/nvidia-persistenced/socket]                                                                                  tmpfs    rw,nosuid,nodev,noexec,relatime,size=3280712k,mode=755

**Comment by schroeder-dewitt** [comment] 2018-03-20 21:11
any ideas?

**Comment by flx42** [comment] 2018-03-21 01:30
Not really. @3XX0 ?

**Comment by schroeder-dewitt** [comment] 2018-03-24 12:52
no, it doesn't. so is this an issue with the underlying docker image then? whom should I contact? are you able to reproduce the issue? thanks!

**Comment by flx42** [comment] 2018-03-24 16:14
File an issue here:
https://github.com/moby/moby
And no, I've never seen this issue.

**Comment by 3XX0** [comment] 2018-03-24 20:37
Be sure to mention your docker daemon options as it may be the cause of your issue (e.g. `--no-new-privileges`)

**Closed** 2018-03-29 22:42 UTC
