### ISSUE TITLE
nvidia-container-cli timeout on p2.16xlarge EC2 instance

### ISSUE THREAD

**Issue by mattdornfeld** [NVIDIA/nvidia-docker#628] opened 2018-02-06 21:55 UTC
I get an error when trying to use Nvidia Docker on the 16 GPU EC2 instances. It seems like nvidia-container-cli is hitting some kind of timeout when trying to list all of the GPUs. I have no trouble getting it to work on the 8 GPU EC2 instances. Is there a way I can increase the timeout period?

```
root@ip-10-206-45-133:/home/ubuntu# nvidia-docker run -it b0390e3560b4 bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"process_linux.go:381: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --utility --pid=16242 /var/lib/docker/overlay2/c2b56038bde0fb7e5ee3864ee52c18da583727fbf0f01530c5359488cde53ae8/merged]\\\\nnvidia-container-cli: initialization error: driver error: timed out\\\\n\\\"\"": unknown.
```

**Comment by mattdornfeld** [comment] 2018-02-06 22:13
@3XX0 I did some research and was planning on running nvidia-persistenced as systemd service. Do you have any other suggestions?

**Comment by flx42** [comment] 2018-02-06 22:33
Yep, that's what you should do.
There is a way to do that quite easily, run the following as root:
```
cd /usr/share/doc/NVIDIA_GLX-1.0/sample/
tar xvjf nvidia-persistenced-init.tar.bz2
nvidia-persistenced-init/install.sh
```

**Comment by 3XX0** [comment] 2018-02-08 22:16
@mattdornfeld does the above fix the issue?

**Comment by pineking** [comment] 2018-02-10 06:40
@3XX0 I built and run https://github.com/NVIDIA/k8s-device-plugin/commit/dbc8590bb06bd57284bfb2c787b7f7721135c01b, meet the same issue:
```
kubectl logs -n=kube-system nvidia-device-plugin-daemonset-d48w6
container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"process_linux.go:351: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --utility --pid=14508 /var/lib/docker/overlay2/ce71005f5f75644e1ead31000132b32f259fef9734d4f5df876a31b94b3d580e/merged]\\\\nnvidia-container-cli: initialization error: driver error: timed out\\\\n\\\"\""
```
and it could be fixed by setting GPU to persistence mode as @flx42 described.

**Comment by 3XX0** [comment] 2018-02-10 07:07
Glad you fixed it, I will increase the timeout

**Closed by 3XX0** 2018-02-10 07:07 UTC

**Comment by netw0rkf10w** [comment] 2018-06-05 08:21
@3XX0 Hello. I got the same error and followed your suggestion to enable the persistence mode (the command `sudo nvidia-persistenced --persistence-mode` did not work so I did `sudo nvidia-smi -pm ENABLED`). After that, when doing `nvidia-smi` it showed instantly the output, and the above timed out error did not occur when running `nvidia-docker`. **However, when one of the GPU is used (a lot) by an external python process (outside docker)**:

![gpu1](https://user-images.githubusercontent.com/8569515/40963702-8bbea384-68a9-11e8-8b1c-d2aabbb9a805.png)

then, again, `nvidia-smi` becomes very slow and `nvidia-docker` outputs a timed out error.

Could you please help me?

If there is no other solution than increase the timeout limit, then could you please show me how to do that?

Thank you very much in advance for your help!

**Comment by 3XX0** [comment] 2018-06-05 21:30
@netw0rkf10w This is most likely a driver issue

**Comment by netw0rkf10w** [comment] 2018-06-08 08:55
@3XX0 Thanks for your reply. But I'm already using the latest version for Ubutnu 16.04 and CUDA 9.0, which is 384.130?

**Comment by netw0rkf10w** [comment] 2018-06-14 12:13
@3XX0 Could you please tell me how to increase the timeout limit?
Thank you in advance for your help!

**Comment by chengxiangwang** [comment] 2018-11-17 13:58
default timeout 10,i recommended to add as a configuration item
[source code](https://github.com/NVIDIA/libnvidia-container/blob/master/src/driver.c)

**Comment by quelle1** [comment] 2019-09-19 00:38
I solve this problem with Re-insert  RTX2080Ti. (ubuntu 18.04, cuda10.0 ,driver 410.48)
First I take off my graphics card （RTX 2080TI, `lspci | grep -i nividia` command results is  NVIDIA Corporation GV102）,
Second I replace this graphic card by another RTX 2080Ti （`lspci | grep -i nividia` results is NVIDIA Corporation Device 1e04）, than the problem is resloved. then the nvidia-docker can start a container.

**Comment by mbiokyle29** [comment] 2021-03-31 16:33
I also experience this issue when trying to run GPU jobs on AWS Batch. SSH'ing into the underlying ECS instance (a p2.16xlarge) and running the above command (`sudo nvidia-smi -pm ENABLED`), fixed it for me.
