### ISSUE TITLE
Segfault when launching a container

### ISSUE THREAD

**Issue by dbason** [NVIDIA/nvidia-docker#1535] opened 2021-08-16 02:11 UTC
### 1. Issue or feature description
Can run a GPU workload.  I'm running on WSL2 but this doesn't seem related to that (this is the same issue as #1533 which has been closed)
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: signal: segmentation fault, stdout: , stderr:: unknown.
ERRO[0000] error waiting for container: context canceled
```

This may be related to the fact it is running on ubuntu 18.04.  Downgrading to the libnvidia 1.4.0 packages stops the issue occurring
### 2. Steps to reproduce the issue
```
docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
```
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
 - [ ] Kernel version from `uname -a`
 - [x] Any relevant kernel output lines from `dmesg`
 ```
[  317.086889] nvidia-containe[6941]: segfault at 0 ip 00007f0aff4d2c6a sp 00007ffe08482048 error 4 in libc-2.27.so[7f0aff429000+1e7000]
[  317.086894] Code: 0f b6 0e 0f b6 07 29 c8 c3 0f 1f 80 00 00 00 00 89 f8 31 d2 66 0f ef ff 09 f0 25 ff 0f 00 00 3d c0 0f 00 00 0f 8f 78 02 00 00 <f3> 0f 6f 0f f3 0f 6f 06 66 0f 74 c1 66 0f da c1 66 0f ef c9 66 0f
[  317.086895] potentially unexpected fatal signal 11.
[  317.086896] CPU: 12 PID: 6941 Comm: nvidia-containe Not tainted 5.10.43.3-microsoft-standard-WSL2 #1
[  317.086901] RIP: 0033:0x7f0aff4d2c6a
[  317.086902] Code: 0f b6 0e 0f b6 07 29 c8 c3 0f 1f 80 00 00 00 00 89 f8 31 d2 66 0f ef ff 09 f0 25 ff 0f 00 00 3d c0 0f 00 00 0f 8f 78 02 00 00 <f3> 0f 6f 0f f3 0f 6f 06 66 0f 74 c1 66 0f da c1 66 0f ef c9 66 0f
[  317.086904] RSP: 002b:00007ffe08482048 EFLAGS: 00010287
[  317.086906] RAX: 00000000000007dd RBX: 000055f2eba078b0 RCX: 00007f0afee1d7bf
[  317.086907] RDX: 0000000000000000 RSI: 00007f0afee1d7dd RDI: 0000000000000000
[  317.086908] RBP: 000055f2eba078b8 R08: 000000000000fffe R09: 000000000000fffe
[  317.086909] R10: 00007f0aff5c7c40 R11: 0000000000000206 R12: 000055f2eba07950
[  317.086910] R13: 0000000000000001 R14: 0000000000000000 R15: 000055f2eba079b0
[  317.086912] FS:  00007f0affa34f80 GS:  0000000000000000
```
 - [x] Driver information from `nvidia-smi -a`
```
Timestamp                                 : Mon Aug 16 14:06:16 2021
Driver Version                            : 471.21
CUDA Version                              : 11.4

Attached GPUs                             : 1
GPU 00000000:01:00.0
    Product Name                          : NVIDIA GeForce RTX 2070 Super
    Product Brand                         : GeForce
    Display Mode                          : Enabled
    Display Active                        : Enabled
```
 - [ ] Docker version from `docker version`
 - [x] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 ```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                           Version                      Architecture                 Description
+++-==============================================-============================-============================-=================================================================================================
un  libgldispatch0-nvidia                          <none>                       <none>                       (no description available)
ii  libnvidia-container-tools                      1.5.0~rc.1-1                 amd64                        NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64                     1.5.0~rc.1-1                 amd64                        NVIDIA container runtime library
un  nvidia-304                                     <none>                       <none>                       (no description available)
un  nvidia-340                                     <none>                       <none>                       (no description available)
un  nvidia-384                                     <none>                       <none>                       (no description available)
ii  nvidia-container-runtime                       3.5.0-1                      amd64                        NVIDIA container runtime
un  nvidia-container-runtime-hook                  <none>                       <none>                       (no description available)
ii  nvidia-container-toolkit                       1.5.1-1                      amd64                        NVIDIA container runtime hook
un  nvidia-docker                                  <none>                       <none>                       (no description available)
ii  nvidia-docker2                                 2.6.0-1                      all                          nvidia-docker CLI wrapper
```
 - [x] NVIDIA container library version from `nvidia-container-cli -V`
 ```
version: 1.5.0~rc.1
build date: 2021-08-13T09:32+00:00
build revision: 5884d4232da9109423f55e79d57df264991c27cf
build compiler: x86_64-linux-gnu-gcc-7 7.5.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections
```
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [x] Docker command, image and tag used
 ```
docker run --gpus all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
```

**Comment by poojaprabhu28** [comment] 2021-08-16 03:57
I have the same issue. My system details are:
AWS p2-xl machine with Tesla K80 GPU 
ubuntu 18.04
Nvidia Driver 470.57.02
CUDA 11.4

The code I'm trying to execute on the server CLI uses GPU without issue. But it does not trigger GPU utilization inside docker environment

When I try to use the flag --gpus all to create container, I get the following error:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: signal: segmentation fault (core dumped), stdout: , stderr:: unknown.
ERRO[0010] error waiting for container: context canceled

This error come up only for containers trying to use GPU

Please help!

**Comment by dbason** [comment] 2021-08-16 04:28
Try running
```
apt install libnvidia-container1=1.4.0-1 libnvidia-container-tools=1.4.0-1 nvidia-container-toolkit=1.5.1-1
```

To downgrade the libraries

**Comment by elezar** [comment] 2021-08-16 09:26
Hi. Yes, there is an issue in the `rc.1` packages that were released on Friday to the `experimental` repos. We have removed these packages from the repos while we work on the fix. Using the versions from the `stable` repos should address the issues.

**Comment by elezar** [comment] 2021-08-17 07:55
This is a duplicate of #1533. There is a bug in `libnvidia-container-tools-1.5.0~rc.1`.

**Closed** 2021-08-17 07:57 UTC

**Comment by poojaprabhu28** [comment] 2021-08-20 06:45
> This is a duplicate of #1533. There is a bug in libnvidia-container-tools-1.5.0~rc.1. Closing this issue. Please reopen if required.

Downgrading the packages resolved the issue. Thank you!
