### ISSUE TITLE
I cannot add nvidia runtime and cannot run NGC image with OCI error

### ISSUE THREAD

**Issue by thdrl** [NVIDIA/nvidia-docker#751] opened 2018-06-02 18:11 UTC
### 1. Issue or feature description

nvidia-docker cannot run image from nvidia GPU Cloud. So i tried to add runtime manually but fail with following errorlog:
```
thdr@host$ sudo dockerd --add-runtime=nvidia=/usr/bin/nvidia-container-runtime
unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: runtimes: (from flag: [nvidia], from file: map[nvidia:map[path:/usr/bin/nvidia-container-runtime runtimeArgs:[]]])
```

I tried `nvidia-docker` and `nvidia-docker2` but fail with same error. How can i fix OCI error?

#### run docker image

```
thdr@host$ sudo nvidia-docker run -it --rm nvcr.io/nvidia/tensorflow:18.05-py3 bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods --debug=/var/log/nvidia-container-runtime-hook.log --ldcache=/etc/ld.so.cache configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --compat32 --graphics --utility --video --display --require=cuda>=9.0 --pid=20001 /var/lib/docker/overlay2/be1fd00ec864cf8e384463ac6772c02a2df30feb54bb04a4d79e4d1ccdbce2bd/merged]\\\\nnvidia-container-cli: ldcache error: process /sbin/ldconfig.real terminated with signal 11\\\\n\\\"\"": unknown.
```

So i tried to follow [Docker Engine Setup](https://github.com/NVIDIA/nvidia-container-runtime#docker-engine-setup) from nvidia-container-runtime. But it doesn't work.

#### restart docker for override.conf

```
thdr@host $ sudo systemctl restart docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
thdr@host $ sudo systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─override.conf
   Active: inactive (dead) (Result: exit-code) since Sun 2018-06-03 02:59:34 KST; 14s ago
     Docs: https://docs.docker.com
  Process: 20143 ExecStart=/usr/bin/dockerd --host=fd:// --add-runtime=nvidia=/usr/bin/nvidia-container-runtime (code=exited, status=1/FAILURE)
 Main PID: 20143 (code=exited, status=1/FAILURE)

Jun 03 02:59:34 host systemd[1]: Failed to start Docker Application Container Engine.
Jun 03 02:59:34 host systemd[1]: docker.service: Unit entered failed state.
Jun 03 02:59:34 host systemd[1]: docker.service: Failed with result 'exit-code'.
Jun 03 02:59:34 host systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Jun 03 02:59:34 host systemd[1]: Stopped Docker Application Container Engine.
Jun 03 02:59:34 host systemd[1]: docker.service: Start request repeated too quickly.
Jun 03 02:59:34 host systemd[1]: Failed to start Docker Application Container Engine.
```

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] Kernel version from `uname -a`

`Linux-image-4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`
 - [x] Any relevant kernel output lines from `dmesg`

```
[31966.129104] docker0: port 1(veth27f858b) entered forwarding state
[31966.129130] docker0: port 1(veth27f858b) entered forwarding state
[31966.333160] traps: nvc:[ldconfig][19783] general protection ip:7fe554a87196 sp:7fff70c9ff90 error:0 in libc-2.23.so[7fe554a50000+1c0000]
[31966.510177] docker0: port 1(veth27f858b) entered disabled state
```
 - [x] Driver information from `nvidia-smi -a`

`384.130`

 - [x] Docker version from `docker version`

```

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

 - [x] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`

```
 Name                                          Version                     Architecture                Description
+++-=============================================-===========================-===========================-================================================================================================
ii  libnvidia-container-tools                     1.0.0~rc.1-1                amd64                       NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64                    1.0.0~rc.1-1                amd64                       NVIDIA container runtime library
un  mate-sensors-applet-nvidia                    <none>                      <none>                      (no description available)
ii  nvidia-384                                    384.130-0ubuntu0.16.04.1    amd64                       NVIDIA binary driver - version 384.130
ii  nvidia-384-dev                                384.130-0ubuntu0.16.04.1    amd64                       NVIDIA binary Xorg driver development files
un  nvidia-common                                 <none>                      <none>                      (no description available)
ii  nvidia-container-runtime                      2.0.0+docker18.03.1-1       amd64                       NVIDIA container runtime
ii  nvidia-container-runtime-hook                 1.3.0-1                     amd64                       NVIDIA container runtime hook
rc  nvidia-docker                                 1.0.1-1                     amd64                       NVIDIA Docker container tools
ii  nvidia-docker2                                2.0.3+docker18.03.1-1       all                         nvidia-docker CLI wrapper
un  nvidia-driver-binary                          <none>                      <none>                      (no description available)
un  nvidia-libopencl1-384                         <none>                      <none>                      (no description available)
un  nvidia-libopencl1-dev                         <none>                      <none>                      (no description available)
ii  nvidia-modprobe                               384.81-0ubuntu1             amd64                       Load the NVIDIA kernel driver and create device files
un  nvidia-opencl-icd                             <none>                      <none>                      (no description available)
ii  nvidia-opencl-icd-384                         384.130-0ubuntu0.16.04.1    amd64                       NVIDIA OpenCL ICD
un  nvidia-persistenced                           <none>                      <none>                      (no description available)
un  nvidia-prime                                  <none>                      <none>                      (no description available)
ii  nvidia-settings                               396.24-0ubuntu0~gpu16.04.1  amd64                       Tool for configuring the NVIDIA graphics driver
un  nvidia-settings-binary                        <none>                      <none>                      (no description available)
un  nvidia-smi                                    <none>                      <none>                      (no description available)
```

 - [x] NVIDIA container library version from `nvidia-container-cli -V`

`version: 1.0.0`

 - [x] Docker command, image and tag used

```
nvidia-docker run -it --rm nvcr.io/nvidia/tensorflow:18.05-py3
```

**Comment by flx42** [comment] 2018-06-03 03:08
There are two different problems here:

# Issue 1
```
thdr@host$ sudo dockerd --add-runtime=nvidia=/usr/bin/nvidia-container-runtime
unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: runtimes: (from flag: [nvidia], from file: map[nvidia:map[path:/usr/bin/nvidia-container-runtime runtimeArgs:[]]])
```
You registered the runtime twice, see https://github.com/NVIDIA/nvidia-docker/issues/749#issuecomment-393002402


# Issue 2
```
thdr@host$ sudo nvidia-docker run -it --rm nvcr.io/nvidia/tensorflow:18.05-py3 bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods --debug=/var/log/nvidia-container-runtime-hook.log --ldcache=/etc/ld.so.cache configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --compat32 --graphics --utility --video --display --require=cuda>=9.0 --pid=20001 /var/lib/docker/overlay2/be1fd00ec864cf8e384463ac6772c02a2df30feb54bb04a4d79e4d1ccdbce2bd/merged]\\\\nnvidia-container-cli: ldcache error: process /sbin/ldconfig.real terminated with signal 11\\\\n\\\"\"": unknown.
```
This is the same issue as https://github.com/NVIDIA/nvidia-docker/issues/746
We don't have a fix yet, what is the output of `docker info` on your machine?

**Comment by thdrl** [comment] 2018-06-03 05:34
Thank you for your comment.

The issue 1, i thought like you too, but cannot resolve without remove and re-install `nvidia-container-runtime`. Anyway, i solve this problem with re-install.

For the issue 2, i paste `docker info` from my machine:

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local nvidia-docker
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-53-generic
Operating System: Linux Mint 18.1
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.76GiB
Name: iislab
ID: QATG:4IPG:NBFT:WEGO:DSUD:25PS:LSXL:2OFA:A3WA:F7AY:2GAH:XWIS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

Thank you.

**Comment by 3XX0** [comment] 2018-06-04 23:30
Duplicate of #746

**Closed by 3XX0** 2018-06-04 23:30 UTC
