### ISSUE TITLE
signal: segmentation fault (core dumped), stdout: , stderr:: unknown. When install the docker nvidia 

### ISSUE THREAD

**Issue by lelechen63** [NVIDIA/nvidia-docker#1536] opened 2021-08-16 15:49 UTC
### 1. Issue or feature description
Follow the instruction in: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html,
in this step: sudo docker run --rm --gpus all nvidia/cuda:10.2-base nvidia-smi

It shows: docker: **Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: signal: segmentation fault (core dumped), stdout: , stderr:: unknown.**

### 2. Steps to reproduce the issue
**docker -v**
Docker version 20.10.7, build f0df350

**docker run hello-world**

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

 **sudo docker run --rm --gpus all nvidia/cuda:10.2-base nvidia-smi**
WARNING: Error loading config file: /u/lchen63/.docker/config.json: open /u/lchen63/.docker/config.json: permission denied
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: signal: segmentation fault (core dumped), stdout: , stderr:: unknown.

**Comment by lelechen63** [comment] 2021-08-16 15:50
**nvidia-smi**
Mon Aug 16 11:47:45 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN Xp            On   | 00000000:01:00.0 Off |                  N/A |
| 23%   21C    P8     8W / 250W |      1MiB / 12194MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN X (Pascal)    On   | 00000000:02:00.0 Off |                  N/A |
| 23%   25C    P8     9W / 250W |      1MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  TITAN X (Pascal)    On   | 00000000:03:00.0 Off |                  N/A |
| 23%   24C    P8     8W / 250W |      1MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by ZhiluDing** [comment] 2021-08-17 02:49
@lelechen63 did you resolve this problem? I got totally same error msg with sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi

**Comment by ZhiluDing** [comment] 2021-08-17 03:04
@lelechen63 hi, I just resolve this problem with downgrade
apt install libnvidia-container1=1.4.0-1 libnvidia-container-tools=1.4.0-1 nvidia-container-toolkit=1.5.1-1
seems the rc.1 packages cause this problem.
hope it works for u. [https://github.com/NVIDIA/nvidia-docker/issues/1534](url)

**Comment by elezar** [comment] 2021-08-17 07:56
This is a duplicate of #1533. There is a bug in libnvidia-container-tools-1.5.0~rc.1. Please downgrade to the latest stable version. Closing this issue.

**Closed by elezar** 2021-08-17 07:56 UTC
