### ISSUE TITLE
docker attach, ps  hang

### ISSUE THREAD

**Issue by jeremy-rutman** [NVIDIA/nvidia-docker#93] opened 2016-05-08 09:46 UTC
this is similar to issue [12606](https://github.com/docker/docker/issues/12606) but it was suggested there to start a new thread for version 1.10.  It is the same as [22488](https://github.com/docker/docker/issues/22488#issuecomment-217250412) where someone suggested to open the issue in nvidia-docker .

**Output of `docker version`:**  
```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
root@braini2:~# uname -a
Linux braini2 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 111
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local nvidia-docker
 Network: bridge null host
Kernel Version: 3.13.0-79-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 125.8 GiB
Name: braini2
ID: DZAL:ZG3Z:OT6A:33IF:LSQP:B6ZA:R3AI:C3VF:X2HH:EGE3:NCEL:3HGM
WARNING: No swap limit support
Labels:
 provider=generic
```

ibm softlayer machine , ubuntu 
```
root@braini2:~# uname -a
Linux braini2 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Steps to reproduce the issue:**
A.fire up a container
```
nvidia-docker run -i -t -v /home/jeremy:/root/imgdbs --device /dev/nvidia0:/dev/nvidia0  /dev/nvidia1:/dev/nvidia1 --device /dev/nvidiactl:/dev/nvidiactl --device /dev/nvidia-uvm:/dev/nvidia-uvm 9632089ae495 /bin/bash
```

B. wait a couple days

Docker attach hangs, docker ps hangs after some days. Another container that was started with a similar command (but with --device gpu0 only , not both gpu0 and gpu1) is still running fine.  I guess i can avoid this being a showstopper by writing my periodic output to a linked directory, but its pretty annoying to not be able to use docker ps, and in any case has already lost a week of GPU work unless I can somehow get back into the stuck container...so if anyone has some ideas I'd appreciate it

fwiw the latest nvidia log from apr 21 (docker container froze May 3)  looks like this:
```
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:22:02 Successfully terminated
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:24:57 Loading NVIDIA management library
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:25:00 Loading NVIDIA unified memory
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:25:00 Discovering GPU devices
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:25:00 Provisioning volumes at /var/lib/nvidia-docker/volumes
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:25:00 Serving plugin API at /var/lib/nvidia-docker
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:25:00 Serving remote API at localhost:3476
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:25:02 Received activate request
/usr/bin/nvidia-docker-plugin | 2016/04/21 16:25:02 Plugins activated [VolumeDriver]
```
The docker logfile (from May3 ) doesnt seem to have timestamps and is in this munged-up format:
```
^[[34mINFO^[[0m[1039443] Container 98fbc03c7428ca371fc7a33f1138d51b0f717e8d7036247006c957c7ce0a7014 failed to exit within 10 seconds of $
^[[31mERRO^[[0m[1046081] attach: stdout: write unix /var/run/docker.sock->@: write: broken pipe
```
Now I have the interesting problem that autocomplete of docker attach hangs, so I can't reattach to the remaining not-frozen container without knowing its full name, which was one of those autogeneterated ones, either 'mad_davinci' or the like, or 'condescending_something' where something is something i can't remember as i never had to type it, and docker ps  hangs so I can't get a list...

**Comment by flx42** [comment] 2016-05-08 18:16
I think when @3XX0 asked you to file a bug here, it was regarding this comment only:
https://github.com/docker/docker/issues/22488#issuecomment-217095332
If you have a **different** machine with the same issue, can you try the following command?
```
$ nvidia-docker run --rm nvidia/cuda nvidia-smi
```
Please tell us how you installed nvidia-docker and which version did you use (or when did you install it, if you remember).

It's unlikely that the `docker ps` hang is caused by `nvidia-docker` because you are already past the point where `nvidia-docker` did his job, but we can still take a look.
If you want to find your lost container, you can try to find the ID in this directory:
```
# ls /var/lib/docker/containers
```

**Comment by jeremy-rutman** [comment] 2016-05-10 16:12
ok thanks I will check /var/lib/docker/containers for my lost cargo.
As for the #22488 comment , afaik thats expected behavior (without --device flags, the devices aren't available) - I was responding to someone's comment that I should not be using the --device flags.

**Comment by flx42** [comment] 2016-05-10 16:43
> As for the #22488 comment , afaik thats expected behavior (without --device flags, the devices aren't available) - I was responding to someone's comment that I should not be using the --device flags.

No, `nvidia-docker` is supposed to mount all devices automatically when starting the container, if we detect that the image is using CUDA. 
This is a typical example of the parameters injected automatically by `nvidia-docker`:
```
--volume-driver=nvidia-docker --volume=nvidia_driver_361.57:/usr/local/nvidia:ro --device=/dev/nvidia3 --device=/dev/nvidia2 --device=/dev/nvidia1 --device=/dev/nvidia0 --device=/dev/nvidiactl --device=/dev/nvidia-uvm
```
We do that in order to relieve the user from the burden of mounting all devices and driver files manually.

**Comment by flx42** [comment] 2016-05-16 16:45
@jeremy-rutman any update?

**Comment by flx42** [comment] 2016-05-25 04:56
@jeremy-rutman ping?

**Comment by flx42** [comment] 2016-05-26 18:28
Looking at https://github.com/docker/docker/issues/22488, it seems your issue is fixed? Closing for now, you can reopen an issue if you stumble into problems with the latest `nvidia-docker`.

**Closed by flx42** 2016-05-26 18:28 UTC
