### ISSUE TITLE
Installation failing due to no write permissions on nvidia-docker/

### ISSUE THREAD

**Issue by grisaitis** [NVIDIA/nvidia-docker#50] opened 2016-02-12 13:52 UTC
Sorry, finding a separate issue from my other one (https://github.com/NVIDIA/nvidia-docker/issues/49)... 

Starting from a clean repo, I'm finding that `sudo make install` fails because root can't write to `nvidia-docker/tools/`. Specifically:
```
$ cd ~/src
$ git clone https://github.com/NVIDIA/nvidia-docker
$ cd nvidia-docker/
$ sudo make install
...
Successfully built 3ce152a99c3e
mkdir: cannot create directory ‘<home>/src/nvidia-docker/tools/bin’: Permission denied
make[1]: *** [build] Error 1
make[1]: Leaving directory `<home>/src/nvidia-docker/tools'
make: *** [install] Error 2
```

I was able to fix this by granting write permissions to all users for `nvidia-docker/`, recursively. The original permissions on the folder were `rwxr-xr-x <myself> <myprimarygroup>`.

Should I do something different to make this work out of the box?

**Comment by flx42** [comment] 2016-02-12 21:56
No, out of the box it works fine for multiple people on Ubuntu 14.04. So I'm quite puzzled by your issue since the latest command is ran as root.

Do you have funky `umask` or groups settings maybe?

**Comment by flx42** [comment] 2016-02-19 02:30
Hey,  were you able to figure out if there is anything unusual with your system setup?

**Comment by 3XX0** [comment] 2016-03-01 19:42
Closing the issue for now, I will reopen it if we manage to reproduce it.

**Closed by 3XX0** 2016-03-01 19:42 UTC
Labels: duplicate
