### ISSUE TITLE
[nvidia-docker2] libnvidia-fatbinaryloader.so.384.81: no such file on Nvidia driver 384.111

### ISSUE THREAD

**Issue by jimmyqwy** [NVIDIA/nvidia-docker#662] opened 2018-03-12 03:29 UTC
### 1. Issue or feature description
nvidia-docker2 failed to run nvidia/cuda:9.0 on Nvidia driver 384.111
(Please check the detailed information in section 3)
I tried the modify LD_LIBRARY_PATH, and create symbolic link using libnvidia-fatbinaryloader.so.384.81 -> 384.11, but error still happens.

### 2. Steps to reproduce the issue
sudo docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi
[error message]
nvidia-container-cli: initialization error: driver error: failed to process request
[error in log] :  /var/log/nvidia-container-runtime-hook.log
could not start driver service: load library failed: libnvidia-fatbinaryloader.so.**384.81**: cannot open shared object file: no such file or directory

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

- Information from ldconfig
   -> ldconfig -p | grep -E 'libcuda|libnvidia'
   just list the items about fatbinaryloader.so
   -> libnvidia-fatbinaryloader.so.**384.111** (libc6,x86-64) => /usr/lib/nvidia-384/libnvidia-fatbinaryloader.so.**384.111**
   -> libnvidia-fatbinaryloader.so.384.111 (libc6) => /usr/lib32/nvidia-384/libnvidia-fatbinaryloader.so.**384.111**
     I found that gtk still touch the older version 384.81, so modify the fatbinaryloader might solve the issue?  Anyone got any suggestion, please add the comments below.  Thank you!
     libnvidia-gtk3.so.**384.81** (libc6,x86-64) => /usr/lib/libnvidia-gtk3.so.**384.81**

- Driver information from `nvidia-smi -a`
NVIDIA-SMI 384.111                Driver Version: 384.111    
Quadro P5000 

 - Docker version from `docker version`
    17.12.1-ce

 - NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 -- libnvidia-container-tools         1.0.0\~beta.1-1        amd64                 NVIDIA container runtime library (command-line tools)
 -- libnvidia-container1:amd64        1.0.0\~beta.1-1        amd64                 NVIDIA container runtime library
 -- nvidia-384                        384.111-0ubuntu0.14.0 amd64                 NVIDIA binary driver - version 384.111
 -- nvidia-384-dev                    384.90-0ubuntu0.16.04 amd64                 NVIDIA binary Xorg driver development files

 - NVIDIA container library version from `nvidia-container-cli -V`
version: 1.0.0
build date: 2018-03-06T01:53+00:00
build revision: be797da00b156493e80f1ae6f38d69f23c932554
build compiler: gcc-5 5.4.0 20160609
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

 - CUDA version
    -> cat /usr/local/cuda/version.txt
    -> CUDA Version 9.0.176

**Comment by 3XX0** [comment] 2018-03-12 21:04
You have two conflicting driver installs (i.e. 384.81 and 384.111). Make sure to purge one of them and reboot to make sure the other one gets loaded

**Comment by jimmyqwy** [comment] 2018-03-13 01:58
Hi, @3XX0 Thank you for your comments. 
Actually, I just have one driver installed.  The issue is that latest nvidia-docker2 with cuda 9.0 seems load  libnvidia-fatbinaryloader.so.384.81, which is not existed on the machine with 384.111 version of Nvidia driver....  Do I have to downgrade the driver version from 384.111 to 81?
Thank you!

**Comment by 3XX0** [comment] 2018-03-13 08:00
You clearly have conflicting drivers otherwise you wouldn't have references to 384.81.
I suggest you purge everything, remove all references to nvidia libraries and run `ldconfig` to make sure everything is gone.
Then reinstall `nvidia-384` and `libcuda1-384`

**Comment by jimmyqwy** [comment] 2018-03-15 02:59
Hi, @3XX0
I have purged everything and reinstalled the driver 384.111 and cuda 9.0.
But it still failed with the following error message... 
nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected 
The error message is same as #548.  

deviceQuery and bandwidthTest all PASS.
By the way, I also tried the driver 390.42.  Same error...
Any suggestions?  Thank you!

**Comment by 3XX0** [comment] 2018-03-20 18:43
what's the output of `ldconfig -p | grep -E 'nvidia|cuda'` on the host

**Comment by flx42** [comment] 2018-04-09 17:56
seems like this was caused by a partial driver install. Closing for now.

**Closed by flx42** 2018-04-09 17:56 UTC
Labels: driver issue
