### ISSUE TITLE
detection error: nvml error: function not found

### ISSUE THREAD

**Issue by zhujiangyou** [NVIDIA/nvidia-docker#1280] opened 2020-05-19 09:28 UTC
**info:**
 sudo docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
Unable to find image 'nvidia/cuda:latest' locally
latest: Pulling from nvidia/cuda
7ddbc47eeb70: Already exists 
c1bbdc448b72: Already exists 
8c3b70e39044: Already exists 
45d437916d57: Already exists 
d8f1569ddae6: Already exists 
85386706b020: Pull complete 
ee9b457b77d0: Pull complete 
be4f3343ecd3: Pull complete 
30b4effda4fd: Pull complete 
Digest: sha256:31e2a1ca7b0e1f678fb1dd0c985b4223273f7c0f3dbde60053b371e2a1aee2cd
Status: Downloaded newer image for nvidia/cuda:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: detection error: nvml error: function not found\\\\n\\\"\"": unknown.

**nvidia-smi**
Tue May 19 17:24:46 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:00:03.0 Off |                    0 |
| N/A   29C    P0    45W / 250W |      0MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**nvidia-container-cli -V**
version: 1.1.0
build date: 2020-05-18T12:02+00:00
build revision: d811ca8ddbf6626a19cdb61f8cab4217397aaa88
build compiler: x86_64-linux-gnu-gcc-7 7.5.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

**uname -a**
Linux 192-168-255-103 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 **nvidia-container-cli -k -d /dev/tty info**

-- WARNING, the following logs are for debugging purposes only --

I0519 09:26:02.461517 62967 nvc.c:281] initializing library context (version=1.1.0, build=d811ca8ddbf6626a19cdb61f8cab4217397aaa88)
I0519 09:26:02.461581 62967 nvc.c:255] using root /
I0519 09:26:02.461595 62967 nvc.c:256] using ldcache /etc/ld.so.cache
I0519 09:26:02.461600 62967 nvc.c:257] using unprivileged user 1000:1000
W0519 09:26:02.463113 62968 nvc.c:186] failed to set inheritable capabilities
W0519 09:26:02.463203 62968 nvc.c:187] skipping kernel modules load due to failure
I0519 09:26:02.463549 62969 driver.c:101] starting driver service
I0519 09:26:02.466433 62967 nvc_info.c:541] requesting driver information with ''
nvidia-container-cli: detection error: nvml error: function not found
I0519 09:26:02.466634 62967 nvc.c:318] shutting down library context
I0519 09:26:02.466890 62969 driver.c:156] terminating driver service
I0519 09:26:02.467204 62967 driver.c:196] driver service terminated successfully

 **sudo docker --version**
Docker version 18.06.3-ce, build d7080c1

**Comment by klueska** [comment] 2020-05-19 10:17
Hi @zhujiangyou,

It seems you are using the latest packages we just published last night. I'm curious if this used to work for you and things only started failing after an upgrade, or if this is the first time you are using nvidia-docker.

If this is your first time, could you attempt to downgrade to nvidia-docker2 version 2.2.2 and tell me if you see the same issue? That will help me understand if this is something in the new packages or something else.

**Comment by Joldnine** [comment] 2020-05-19 10:47
We have the same issue here.

**Comment by klueska** [comment] 2020-05-19 11:20
I think I've gotten to the bottom of it.

As part of the `nvidia-docker` 3.2.0 release we removed our dependence on the CUDA runtime in one of the packages that `nvidia-docker` depends on (namely `libnvidia-container`). 

As part of this, the following change was made:
```
-        if (call_cuda(ctx, cuDriverGetVersion, &version) < 0)
+        if (call_nvml(ctx, nvmlSystemGetCudaDriverVersion_v2, &version) < 0)
```

Which changed the way we got the CUDA version injected into `libnvidia-container` as a call to NVML instead of CUDA directly. On the surface, this shouldn't be an issue.

However, we really should have used `nvmlSystemGetCudaDriverVersion` instead of `nvmlSystemGetCudaDriverVersion_v2` because the latter wasn't introduced until driver version `410.72` which artificially put a new minimum supported driver version on the `nvidia-docker` stack.

I can see that @zhujiangyou is running on driver version `410.48` (which is obviously less than `410.72`), and I'm guessing anyone else having this issue is also running on a driver version less than `410.72`.

Let me talk with the team about the best way to address this. In the meantime. I would suggest either downgrading back to `nvidia-docker2` version 2.2.2 or upgrading your driver.

**Comment by zhujiangyou** [comment] 2020-05-19 14:31
> I think I've gotten to the bottom of it.
> 
> As part of the `nvidia-docker` 3.2.0 release we removed our dependence on the CUDA runtime in one of the packages that `nvidia-docker` depends on (namely `libnvidia-container`).
> 
> As part of this, the following change was made:
> 
> ```
> -        if (call_cuda(ctx, cuDriverGetVersion, &version) < 0)
> +        if (call_nvml(ctx, nvmlSystemGetCudaDriverVersion_v2, &version) < 0)
> ```
> 
> Which changed the way we got the CUDA version injected into `libnvidia-container` as a call to NVML instead of CUDA directly. On the surface, this shouldn't be an issue.
> 
> However, we really should have used `nvmlSystemGetCudaDriverVersion` instead of `nvmlSystemGetCudaDriverVersion_v2` because the latter wasn't introduced until driver version `410.72` which artificially put a new minimum supported driver version on the `nvidia-docker` stack.
> 
> I can see that @zhujiangyou is running on driver version `410.48` (which is obviously less than `410.72`), and I'm guessing anyone else having this issue is also running on a driver version less than `410.72`.
> 
> Let me talk with the team about the best way to address this. In the meantime. I would suggest either downgrading back to `nvidia-docker2` version 2.2.2 or upgrading your driver.

Thinks, i will try it !

**Comment by shawks03** [comment] 2020-05-19 17:46
Yeah, I faced the same problem. Downgrading to the follow versions makes it work again:
sudo apt-get install -y libnvidia-container1=1.0.7-1
sudo apt-get install -y libnvidia-container-tools=1.0.7-1
sudo apt-get install -y nvidia-container-toolkit=1.0.5-1
sudo apt-get install -y nvidia-container-runtime=3.1.4-1
sudo apt-get install -y nvidia-docker2=2.2.2-1

I've seen this on Ubuntu 16.04 (nvidia 384.130) and Ubuntu 18.04 (nvidia 390.132).

**Comment by klueska** [comment] 2020-05-19 21:52
New packages have been published that should resolve this issue. Please run one of the following depending on your platform:

```
sudo apt-get install nvidia-container-toolkit
```
```
sudo yum install nvidia-container-toolkit
```

If you originally installed `nvidia-docker2` and not `nvidia-container-toolkit`, you should still run the commands above in order to update `nvidia-docker2` properly (it has a dependence on `nvidia-container-toolkit` that will now be upgraded).

**Comment by klueska** [comment] 2020-05-20 10:18
Please confirm if the new packages resolve your issue and close this issue if so.

**Comment by shawks03** [comment] 2020-05-21 19:35
@klueska I can confirm on Ubuntu 18.04 the new packages resolve the issue. I didn't try Ubuntu 16.04, but I assume that works too.

**Comment by zhujiangyou** [comment] 2020-05-22 11:21
@klueska I have confirmed that the new packages can resolve the issue !

**Closed** 2020-05-22 11:34 UTC

**Comment by frederico-klein** [comment] 2020-08-10 18:08
> Yeah, I faced the same problem. Downgrading to the follow versions makes it work again:
> sudo apt-get install -y libnvidia-container1=1.0.7-1
> sudo apt-get install -y libnvidia-container-tools=1.0.7-1
> sudo apt-get install -y nvidia-container-toolkit=1.0.5-1
> sudo apt-get install -y nvidia-container-runtime=3.1.4-1
> sudo apt-get install -y nvidia-docker2=2.2.2-1
> 
> I've seen this on Ubuntu 16.04 (nvidia 384.130) and Ubuntu 18.04 (nvidia 390.132).

this works for me if I add --allow-downgrades on all of them. 

The new nvidia-container-toolkit does not, but I am using very old drivers ( Ubuntu 18.04 with nvidia 340.108) to get my GTX 580 to run a docker. I got ` nvidia/cuda:6.5-devel` to run cuda opencv2 with this set- up

**Comment by dmvuong95** [comment] 2020-12-22 19:41
> > Yeah, I faced the same problem. Downgrading to the follow versions makes it work again:
> > sudo apt-get install -y libnvidia-container1=1.0.7-1
> > sudo apt-get install -y libnvidia-container-tools=1.0.7-1
> > sudo apt-get install -y nvidia-container-toolkit=1.0.5-1
> > sudo apt-get install -y nvidia-container-runtime=3.1.4-1
> > sudo apt-get install -y nvidia-docker2=2.2.2-1
> > I've seen this on Ubuntu 16.04 (nvidia 384.130) and Ubuntu 18.04 (nvidia 390.132).
> 
> this works for me if I add `--allow-downgrades` on all of them.
> 
> The new nvidia-container-toolkit does not, but I am using very old drivers ( Ubuntu 18.04 with nvidia 340.108) to get my GTX 580 to run a docker. I got ` nvidia/cuda:6.5-devel` to run cuda opencv2 with this set- up

That's awesome. Thank u

**Comment by aoqixiaoning** [comment] 2021-02-24 07:13
info:
Shared directory: /home/zn/shared_dir
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: detection error: nvml error: unknown error: unknown.

nvidia-smi
Wed Feb 24 15:11:21 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.64       Driver Version: 430.64       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  ERR!                Off  | 00000000:01:00.0  On |                  N/A |
| N/A   39C    P8     5W /  N/A |    202MiB /  5926MiB |     12%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1232      G   /usr/lib/xorg/Xorg                           150MiB |
|    0      2159      G   compiz                                        38MiB |
|    0      3080      G   /usr/lib/firefox/firefox                       3MiB |
|    0      3601      G   /usr/lib/firefox/firefox                       3MiB |
|    0     20026      G   /usr/lib/firefox/firefox                       3MiB |
+-----------------------------------------------------------------------------+


nvidia-container-cli -V
version: 1.3.3
build date: 2021-02-05T13:29+00:00
build revision: bd9fc3f2b642345301cb2e23de07ec5386232317
build compiler: gcc-5 5.4.0 20160609
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections


uname -a
Linux zn-Lenovo-Legion-R7000P2020H 5.2.20-050220-generic #201910071832 SMP Mon Oct 7 18:35:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux


nvidia-container-cli -k -d /dev/tty info

-- WARNING, the following logs are for debugging purposes only --

I0224 07:12:22.076521 20384 nvc.c:372] initializing library context (version=1.3.3, build=bd9fc3f2b642345301cb2e23de07ec5386232317)
I0224 07:12:22.076566 20384 nvc.c:346] using root /
I0224 07:12:22.076575 20384 nvc.c:347] using ldcache /etc/ld.so.cache
I0224 07:12:22.076585 20384 nvc.c:348] using unprivileged user 1000:1000
I0224 07:12:22.076610 20384 nvc.c:389] attempting to load dxcore to see if we are running under Windows Subsystem for Linux (WSL)
I0224 07:12:22.076835 20384 nvc.c:391] dxcore initialization failed, continuing assuming a non-WSL environment
W0224 07:12:22.078383 20385 nvc.c:269] failed to set inheritable capabilities
W0224 07:12:22.078430 20385 nvc.c:270] skipping kernel modules load due to failure
I0224 07:12:22.078899 20386 driver.c:101] starting driver service


sudo docker --version
Docker version 20.10.3, build 48d30b5

**Comment by aoqixiaoning** [comment] 2021-02-25 11:48
info:
Shared directory: /home/zn/shared_dir
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: detection error: nvml error: unknown error: unknown.

nvidia-smi
Wed Feb 24 15:11:21 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.64 Driver Version: 430.64 CUDA Version: 10.1 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 ERR! Off | 00000000:01:00.0 On | N/A |
| N/A 39C P8 5W / N/A | 202MiB / 5926MiB | 12% Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes: GPU Memory |
| GPU PID Type Process name Usage |
|=============================================================================|
| 0 1232 G /usr/lib/xorg/Xorg 150MiB |
| 0 2159 G compiz 38MiB |
| 0 3080 G /usr/lib/firefox/firefox 3MiB |
| 0 3601 G /usr/lib/firefox/firefox 3MiB |
| 0 20026 G /usr/lib/firefox/firefox 3MiB |
+-----------------------------------------------------------------------------+

nvidia-container-cli -V
version: 1.3.3
build date: 2021-02-05T13:29+00:00
build revision: bd9fc3f2b642345301cb2e23de07ec5386232317
build compiler: gcc-5 5.4.0 20160609
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

uname -a
Linux zn-Lenovo-Legion-R7000P2020H 5.2.20-050220-generic #201910071832 SMP Mon Oct 7 18:35:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

nvidia-container-cli -k -d /dev/tty info

-- WARNING, the following logs are for debugging purposes only --

I0224 07:12:22.076521 20384 nvc.c:372] initializing library context (version=1.3.3, build=bd9fc3f2b642345301cb2e23de07ec5386232317)
I0224 07:12:22.076566 20384 nvc.c:346] using root /
I0224 07:12:22.076575 20384 nvc.c:347] using ldcache /etc/ld.so.cache
I0224 07:12:22.076585 20384 nvc.c:348] using unprivileged user 1000:1000
I0224 07:12:22.076610 20384 nvc.c:389] attempting to load dxcore to see if we are running under Windows Subsystem for Linux (WSL)
I0224 07:12:22.076835 20384 nvc.c:391] dxcore initialization failed, continuing assuming a non-WSL environment
W0224 07:12:22.078383 20385 nvc.c:269] failed to set inheritable capabilities
W0224 07:12:22.078430 20385 nvc.c:270] skipping kernel modules load due to failure
I0224 07:12:22.078899 20386 driver.c:101] starting driver service

sudo docker --version
Docker version 20.10.3, build 48d30b5

**Comment by elezar** [comment] 2021-02-25 12:12
@aoqixiaoning If you are experiencing problems, please open a new issue describing the behaviour you are seeing.

From your `nvidia-smi` output (which I assume is on the host):
```
nvidia-smi
Wed Feb 24 15:11:21 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.64 Driver Version: 430.64 CUDA Version: 10.1 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 ERR! Off | 00000000:01:00.0 On | N/A |
| N/A 39C P8 5W / N/A | 202MiB / 5926MiB | 12% Default |
+-------------------------------+----------------------+----------------------+
```

It seems as if there is a problem accessing the device on the host as well.

**Comment by elezar** [comment] 2021-02-25 12:12
@aoqixiaoning If you are experiencing problems, please open a new issue describing the behaviour you are seeing.

From your `nvidia-smi` output (which I assume is on the host):
```
nvidia-smi
Wed Feb 24 15:11:21 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.64 Driver Version: 430.64 CUDA Version: 10.1 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 ERR! Off | 00000000:01:00.0 On | N/A |
| N/A 39C P8 5W / N/A | 202MiB / 5926MiB | 12% Default |
+-------------------------------+----------------------+----------------------+
```

It seems as if there is a problem accessing the device on the host as well.

**Comment by elezar** [comment] 2021-02-25 12:14
@aoqixiaoning If you are experiencing problems, please open a new issue describing the behaviour you are seeing.

From your `nvidia-smi` output (which I assume is on the host):
```
nvidia-smi
Wed Feb 24 15:11:21 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.64 Driver Version: 430.64 CUDA Version: 10.1 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 ERR! Off | 00000000:01:00.0 On | N/A |
| N/A 39C P8 5W / N/A | 202MiB / 5926MiB | 12% Default |
+-------------------------------+----------------------+----------------------+
```
It seems as if there is a problem accessing the device on the host as well hence the `ERR!` strings where we would expect the device name to be.
