### ISSUE TITLE
"docker network create" mynet fails with information " unknown flag: --runtime"

### ISSUE THREAD

**Issue by binf027** [NVIDIA/nvidia-docker#867] opened 2018-11-20 16:09 UTC
nvidia-docker1 works well with the docker network create mynet,
but nvidia-docker2 fails, the error message is
"unknown flag: --runtime"

all the other functions work quite well, only except this operation. I can not create my own network any more.

----
$docker network create mynet
unknown flag: --runtime
See 'docker network create --help'.

$docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
9c5d2006ac09        bridge              bridge              local
1370322bd0ef        host                host                local
ed4ad93fb46c        none                null                local

$docker network create --help
unknown flag: --runtime
See 'docker network create --help'.

-----

**Comment by RenaudWasTaken** [comment] 2018-11-23 21:09
Hello!

I can't reproduce your error.
Can you give more context on what you are doing? The issue template is a great place to start :)
 - [ ] Kernel version from `uname -a`
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
 - [ ] Docker version from `docker version`
 - [ ] NVIDIA container library version from `nvidia-container-cli -V`

**Comment by RenaudWasTaken** [comment] 2018-12-20 16:32
Closing as there were no followups.
Feel free to reopen if you have more information!

**Closed by RenaudWasTaken** 2018-12-20 16:32 UTC

**Comment by ktapsyman** [comment] 2019-11-07 02:15
Howdy! Same issue here.
The symptom on my device is that, docker network create always outputs 
_unknown flag: --runtime
See 'docker network create --help'_

no matter what arguments were passed, even for invalid arguments.
docker network create --nosucharg
unknown flag: --runtime
See 'docker network create --help'

**Kernel Info:** 
4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Docker version:**
NVIDIA Docker: 2.2.2
Client: Docker Engine - Community
 Version:           19.03.3-rc1
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        1576bd7917
 Built:             Wed Oct  2 21:23:54 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3-rc1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       1576bd7917
  Built:            Wed Oct  2 21:22:26 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 nvidia:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Nvidia container library version**
version: 1.0.5
build date: 2019-09-06T16:59+00:00
build revision: 13b836390888f7b7c7dca115d16d7e28ab15a836
build compiler: x86_64-linux-gnu-gcc-7 7.4.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections
