### ISSUE TITLE
nvidia-docker for rhel7.6?

### ISSUE THREAD

**Issue by khrishan** [NVIDIA/nvidia-docker#881] opened 2018-12-12 17:26 UTC
### 1. Issue or feature description

```
[root@hostname-removed ~]# distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
[root@hostname-removed ~]# curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.repo | \
>   sudo tee /etc/yum.repos.d/nvidia-docker.repo
# Unsupported distribution!
# Check https://nvidia.github.io/nvidia-docker
```

Will we be getting a version for rhel7.6 - we tested just manually putting the distribution in for 7.5 and it still didn't like it :(

**Comment by treadwm** [comment] 2018-12-13 18:44
I had success on Rhel7.6 running the command this way to get around the issue:

curl -s -L https://nvidia.github.io/nvidia-container-runtime/rhel7.5/nvidia-container-runtime.repo | tee /etc/yum.repos.d/nvidia-container-runtime.repo

**Comment by RenaudWasTaken** [comment] 2018-12-20 16:16
Hello!

I've added support for RHEL 7.6
Closing, feel free to reopen if you hit any issues :)

**Closed by RenaudWasTaken** 2018-12-20 16:16 UTC

**Comment by amrhamedp** [comment] 2019-01-10 03:41
https://nvidia.github.io/nvidia-container-runtime/rhel7.6/nvidia-container-runtime.repo

unsupported distribution

**Comment by qiaohaijun** [comment] 2019-02-12 07:19
https://nvidia.github.io/nvidia-container-runtime/centos7/nvidia-container-runtime.repo

# Unsupported distribution! # Check https://nvidia.github.io/libnvidia-container

**Comment by khrishan** [comment] 2019-04-02 12:33
Hi All

I'm still getting these issues... has anyone found a work around?

**Comment by quetil** [comment] 2019-05-21 16:38
> https://nvidia.github.io/nvidia-container-runtime/centos7/nvidia-container-runtime.repo
> 
> ```
> # Unsupported distribution! # Check https://nvidia.github.io/libnvidia-container
> ```

idem, any solution found?

**Comment by Ethyling** [comment] 2019-05-21 17:19
I can't reproduce the bug on my side with the 3 urls above. Does it work sometimes or never?

**Comment by quevedin** [comment] 2019-09-11 07:03
With the 7.6 hack works
