### ISSUE TITLE
gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by kkvtran** [NVIDIA/nvidia-docker#451] opened 2017-08-09 20:37 UTC
I am trying to build nvidia-docker for RHEL on ppc64le.  I got the following errors
 ---> Running in 80852d199b2a
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.PnJYTdgGE9 --no-auto-check-trustdb --trust-model always --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-stretch-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-stretch-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-stretch-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY
gpgkeys: no key data found for http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
The command '/bin/sh -c NVIDIA_GPGKEY_SUM=bd841d59a27a406e513db7d405550894188a4c1cd96bf8aa4f82f1b39e0b5c1c &&     NVIDIA_GPGKEY_FPR=889bee522da690103c4b085ed88c3d385c37d3be &&     apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/GPGKEY &&     apt-key adv --export --no-emit-version -a $NVIDIA_GPGKEY_FPR | tail -n +2 > cudasign.pub &&     echo "$NVIDIA_GPGKEY_SUM  cudasign.pub" | sha256sum -c --strict - && rm cudasign.pub &&     echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/ppc64el /" > /etc/apt/sources.list.d/cuda.list' returned a non-zero code: 2
make: *** [build] Error 2

From what I can tell, I do not find  GPGKEY in http://developer.download.nvidia.com/compute/cuda/repos

Maybe I missed some set up or something.  Thanks.

**Comment by flx42** [comment] 2017-08-09 20:38
Duplicate of #450

**Closed by flx42** 2017-08-09 20:38 UTC
