### ISSUE TITLE
Server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

### ISSUE THREAD

**Issue by YanzhongSu** [NVIDIA/nvidia-docker#813] opened 2018-08-30 10:55 UTC
I have some problem installing Nvidia-docker. The same issue is [here][1], but unfortunately it does not solve my problem.

My OS is 

> Ubuntu 16.04

.  The kernel info is 

> Linux **** 4.4.0-133-generic #159-Ubuntu SMP Fri Aug 10 07:31:43 UTC
> 2018 x86_64 x86_64 x86_64 GNU/Linux

. 

I followed the installation tutorial here (https://github.com/NVIDIA/nvidia-docker)

When I execute 

`curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -`

Nothing gets crawled. However, if I open the link in Chrome, one gpg file gets downloaded. Any thoughts on why? I then manually add the gpg and get an OK as output which indicates that the key has been added successfully I guess. 

The same issue with 

`curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list`

nothing gets written into the file. So I manually added the following three lines into this file  **/etc/apt/sources.list.d/nvidia-docker.list**

    deb https://nvidia.github.io/libnvidia-container/ubuntu16.04/$(ARCH) /
    deb https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/$(ARCH) /
    deb https://nvidia.github.io/nvidia-docker/ubuntu16.04/$(ARCH) /

But when I execute 

`sudo apt-get update`

I got the following error:

    https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64  Packages
      server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
    https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/amd64  Packages
      server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
    https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64  Packages
      server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
    https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
    https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
    https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

Then when I execute 

`sudo apt-get install –y nvidia-docker2`

it says nvidia-docker2 cannot be located.

I would very thankful if you could give me some guidance on this. Thank you!

  [1]: https://github.com/NVIDIA/nvidia-docker/issues/585

**Comment by 3XX0** [comment] 2018-09-04 20:00
Make sure you have `apt-transport-https` and `ca-certificates` installed and up-to-date.

**Comment by liddellj** [comment] 2018-09-11 09:57
We are also seeing this running a Docker build on Travis CI. Strangely I don't see the issue when I run the same build locally, even after clearing my Docker cache. Here is the first half of our Dockerfile:
```
FROM nvidia/cuda:7.5-devel

RUN apt-get update
RUN apt-get install apt-transport-https -y
RUN sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
RUN apt-get update
RUN apt-get install dotnet-sdk-2.0.0 -y
```

The issue occurs on the third line, `RUN apt-get update`.

**Comment by cwpearson** [comment] 2018-09-13 01:02
I am seeing the exact same issue as @liddellj. It happens during a Docker build on Travis CI, but not when I do the same build locally.

**Comment by YanzhongSu** [comment] 2018-09-20 03:41
> I am seeing the exact same issue as @liddellj. It happens during a Docker build on Travis CI, but not when I do the same build locally.

Hi @cwpearson are you able to solve this problem? I basically have two Ubuntu servers. One has this probelm, the other does not. So I suspect something's wrong with the OS, the base docker image in your case.

**Comment by cwpearson** [comment] 2018-09-20 17:10
Hi, I was having the problem [here](https://travis-ci.com/c3sr/scope/jobs/145433774), for example, on travis.com/c3sr/scope. Now, the corresponding builds are succeeding, so you may be right that there was a problem with the base docker image that has been fixed. I made no changes to resolve the problem.

**Comment by flx42** [comment] 2018-09-20 17:29
@cwpearson the package repositories were being updated for CUDA 10.0. It's often unstable when an upgrade happen, sorry about that.

**Comment by leeskyed** [comment] 2018-10-26 03:18
Have you solve the problem? thx.

**Comment by cwpearson** [comment] 2018-10-27 18:10
@leeskyed, I believe my issue was caused by the problem that @flx42 mentioned. Since then it has been working properly for me.

**Comment by RenaudWasTaken** [comment] 2018-11-23 20:13
Closing as this seems to have been solved. Feel free to re-open.

**Closed by RenaudWasTaken** 2018-11-23 20:13 UTC
